Linux x64 Support
OutSystems/CefGlue pull request #119
Opened 2023-11-20 12:21 UTC by Haltroy

This PR adds support for Linux x64 platform. If asked, the Linux ARM64 platform can be added as well.

Includes edits from PR #88 alongside with my own edits [mentioned in this comment](https://github.com/OutSystems/CefGlue/pull/88#issuecomment-1814829113).

Requires more testing.

2023-11-20 12:24 UTC, Haltroy commented
> I read, understood and accept the OutSystems CLA

2023-11-20 12:25 UTC, Haltroy commented
> Hello @Haltroy 👋
> 
> Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the 📝 [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
> 
> After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

I read, understood and accept the OutSystems CLA

2023-11-20 12:31 UTC, Haltroy commented
Got check errors and have no idea where it happened despite copying differences from PR and it's not letting me to see the errors and now it no longer is working on my system. 

Are CEF wrappers on Linux is cursed or something?

2023-11-20 12:41 UTC, joaompneves requested changes
Thanks for creating this PR. Left some comments.

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/CefGlue.Common.csproj
> +
```suggestion
```

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/CefGlue.Common.csproj
> +
```suggestion
```

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/CefGlue.Common.csproj
> +            <TfmSpecificPackageFile Include="..\CefGlue.BrowserProcess\bin\$(Configuration)\$(DotnetVersion)\linux-x64\publish\**\*">
for consistency and future proof, use the same pattern as the items above

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.props
> +        <CefGlueTargetPlatform Condition="'$(Platform)' == 'x64'">linux-x64</CefGlueTargetPlatform>
since its the only target for linux
```suggestion
        <CefGlueTargetPlatform>linux-x64</CefGlueTargetPlatform>
```

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +
```suggestion
```

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +    <ItemGroup Condition="'$(CefGlueTargetPlatform)' == 'linux'">
```suggestion
    <ItemGroup Condition="'$(CefGlueTargetPlatform)' == 'linux-x64'">
```

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +            <None Include="@(CefRedistLinux64)">
fix indentation

2023-11-20 12:41 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    settings.WindowlessRenderingEnabled = true;
doesn't work with WindowlessRenderingEnabled = false?

2023-11-20 12:47 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    settings.WindowlessRenderingEnabled = true;
Apparently not in my case. It does function (webpage content does load as JS console logs can be seen in console and title of page does change) but won't show anything to screen.

This is why I make this PR draft because this need testing on other distributions and hardware (mine is Intel+NVIDIA Proprietary).

Also, AFAIK CEF does not support sandboxing on Linux. 

If I'm wrong, feel free to comment.

2023-11-20 13:01 UTC, ivanthesexy commented
Did changes, but what about Linux ARM64 and failed checks? 
Also, I can't access logs from failed checks to see what's the issue. On my machine dotnet builds just fine but can't run (missing libcef).

2023-11-20 13:16 UTC, ivanthesexy commented on CefGlue.CopyLocal.props
The "cef.redist.linux64" package on NuGet is owned by PR #88 creator and it's older (current: 117.x NuGet: 106.x)

2023-11-20 13:25 UTC, Haltroy commented
In the checks' outputs, dotnet fails twice with some unknown error (I can't see the log but GitHub displays that it exited with code 1) and fails to restore packages (which is odd since the only addition to packages that I did is available on NuGet but in 106.x instead of current version which is 117.x).

2023-11-20 17:17 UTC, Haltroy commented on CefGlue.Common/build/CefGlue.Common.props
> +        <CefGlueTargetPlatform Condition="'$(Platform)' == 'x64'">linux-x64</CefGlueTargetPlatform>
So we are not planning any Linux ARM64 support?

2023-11-20 17:39 UTC, Haltroy commented on Directory.Build.props
> +        <CefRedistLinuxVersion>117.2.4</CefRedistLinuxVersion>
That's my suspicion too. But why is `dotnet` not telling me anything about it on my system? I did `dotnet restore` with `-v d` just to see any errors that would give it out but nothing.

2023-11-20 17:40 UTC, Haltroy commented
I downloaded the appropriate CEF version and extracted it to the bin folder of demo app, for some reason it is not finding `Xilium.CefGlue.BrowserProcess.dll` (instead there is an executable named `Xilium.CefGlue.BrowserProcess`). It is absent in the demo app's bin folder but it's in the bin folder of `CefGlue.BrowserProcess` and I decided to copy the `linux-x64` build of it to the demo app's bin folder and it worked. Now I have to tell BrowserProcess library to copy itself to the output folder and when the `cef.redist.linux64` gets a appropriate update we are good to go.

2023-11-21 12:54 UTC, Haltroy commented
Still not figured out why BrowserProcess.dll is not getting copied to the output folder. Any help will be appreciated. Also, maintainers are allowed to edit this PR.

2023-11-22 14:27 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    settings.WindowlessRenderingEnabled = true;
WindowlessRenderingEnabled = true ... is not recommended because is less performant and has more issues, because we dont interact directly with the browser but rather an image of it

2023-11-22 14:28 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +            <None Include="@(CefRedistLinux64)">
yet not consistent with the rest of the file

2023-11-22 14:42 UTC, joaompneves commented on Directory.Build.props
> +        <CefRedistLinuxVersion>117.2.4</CefRedistLinuxVersion>
You need to create a package with that version and publish on nuget. 

You may fork this repo and create a linux flavor https://github.com/OutSystems/cef.redist.osx .. and later on we can publish the package under our nuget account.

2023-11-22 16:19 UTC, Haltroy commented on CefGlue.Common/build/CefGlue.Common.targets
> +            <None Include="@(CefRedistLinux64)">
Used the OSX one as a template in the commit https://github.com/OutSystems/CefGlue/pull/119/commits/7f2e20e1735870995a66bc43cba88e6e3fee306a.

2023-11-22 16:28 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    settings.WindowlessRenderingEnabled = true;
I know its issues that's why I said "needs more testing". I'll try it on other distributions but I can't test it on AMD GPUs simply because I don't have any.

For now, I'm going to disable it just to resolve this thing.

2023-11-22 16:30 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    settings.WindowlessRenderingEnabled = true;
Commit https://github.com/OutSystems/CefGlue/pull/119/commits/448675375f94f683edf5bbf39f5b520832455388 is up and disables `WindowlessRenderingEnabled`.

2023-11-22 16:35 UTC, Haltroy commented on Directory.Build.props
> +        <CefRedistLinuxVersion>117.2.4</CefRedistLinuxVersion>
I already know CEF binaries and how they are packaged under other OSes. Linux is packaged the same as Windows is and does not have the same file structure that OSX has.

Also, this is just plain old clogging NuGet and its package names, this means that if you guys do want to publish it under your own brand then you should do it right now. Don't rely on individuals, one day we might stop caring about stuff. This will make your brand cut out support and become out of touch again like these PRs never happened.

I'll make a package under a different name and use it as references just to solve at least one single problem.

2023-11-22 18:20 UTC, Haltroy commented on Directory.Build.props
> +        <CefRedistLinuxVersion>117.2.4</CefRedistLinuxVersion>
Forked the repository but NUSPEC and NuGet are not my strong suits and packing a NUSPEC file alone without a .NET project using dotnet CLI is currently not possible.

[CEF Linux repository](https://github.com/Haltroy/cef.redist.linux)

2023-11-23 16:06 UTC, joaompneves commented on CefGlue.Common/CefGlue.Common.csproj
> +        <PackageReference PrivateAssets="None" Include="cef.redist.linux64" />
created a new [package](https://www.nuget.org/packages/cef.redist.linux.x64/117.2.4) with this name
```suggestion
        <PackageReference PrivateAssets="None" Include="cef.redist.linux-x64" />
```

2023-11-23 16:06 UTC, joaompneves commented on CefGlue.CopyLocal.props
> +        <PackageReference Include="cef.redist.linux64" />
we should have another props file just with this section, so that we dont have to change 2 places
```suggestion
        <PackageReference Include="cef.redist.linux-x64" />
```

2023-11-23 16:06 UTC, joaompneves commented on Directory.Build.props
> +        <CefRedistLinuxVersion>117.2.4</CefRedistLinuxVersion>
I ended up creating a fork because yours want's working:
https://github.com/joaompneves/cef.redist.linux

2023-11-23 16:20 UTC, joaompneves commented on README.md
> +| AMD64    |    x    |   x   |   -   |
ups, my bad
```suggestion
| ARM64    |    x    |   x   |   -   |
```

2023-11-23 16:21 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    // help fix a problem in the future.
nope, I mentioned WindowlessRenderingEnabled, not he sandbox

2023-11-23 16:23 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    // help fix a problem in the future.
You selected 3 lines, which one was closing bracket for another code ("}" which deleting would give you a compile error), the sandbox line and the windowless rendering one.

I'm going to enable NoSandbox again and remove the text if that's OK for you.

2023-11-23 16:23 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    settings.WindowlessRenderingEnabled = false;
Commented out the ***both*** sandbox one and windowless rendering lines while adding a note why.

2023-11-23 16:26 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    // help fix a problem in the future.
yeah, my only concern is WindowlessRenderingEnabled, like we talked before, has several issues

2023-11-23 16:29 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    // help fix a problem in the future.
Since I cannot comment on the DirectoryBuild.props file, I noticed that you forked the #88 's redist. one while telling me to fork this organisation's osx packages. I did what you wanted me to do and in fact it did packaged the redist. however it was >300MB and above NuGet's 250MB limit. (libcef is heavy like 1.3GB heavy). 

I'm fine with who owns what NuGet package as long as I don't have to pack redist. as NuGet by myself.

2023-11-23 16:29 UTC, Haltroy commented on Directory.Build.props
> +        <CefRedistLinuxVersion>117.2.4</CefRedistLinuxVersion>
Since I cannot comment on the DirectoryBuild.props file, I noticed that you forked the https://github.com/OutSystems/CefGlue/pull/88 's redist. one while telling me to fork this organisation's osx packages. I did what you wanted me to do and in fact it did packaged the redist. however it was >300MB and above NuGet's 250MB limit. (libcef is heavy like 1.3GB heavy).

I'm fine with who owns what NuGet package as long as I don't have to pack redist. as NuGet by myself.

2023-11-23 16:33 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +                    // help fix a problem in the future.
https://github.com/OutSystems/CefGlue/pull/119/commits/db38573d12d22772fb9dfff415fb4cf57eeca834 Re-enables NoSandbox mode, leaves the note and comments out the Windowless rendering line in case we need it in the future.

2023-11-23 16:37 UTC, Haltroy commented
We all thought the reason why checks were failing because "dotnet failed to restore" and we all thought that "it's probably because the package on NuGet is pointing to an older version of CEF" and we did change that and still it is failing.

I failed on my task so badly I just want to give up.

2023-11-23 16:38 UTC, joaompneves commented on Directory.Build.props
> +        <CefRedistLinuxVersion>117.2.4</CefRedistLinuxVersion>
I know I did, but then I remembered that 6 months ago the other guy that started the other Linux PR already did part of that job and it was working, while yours was failing, so I ended-up picking up on that. I'm trying to help you, since we're not really interested on linux implementation. I'm just trying to unblock something that can be useful for the community (but not for us at the moment).

2023-11-23 16:40 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +                        settings.LocalesDirPath = localesPath;
to make it consistent with the remaining codebase
```suggestion
                    var localesPath = Path.Combine(basePath, "locales");
                    if (Directory.Exists(localesPath))
                    {
                        settings.LocalesDirPath = localesPath;
                    }
```

2023-11-23 16:41 UTC, joaompneves commented
> We all thought the reason why checks were failing because "dotnet failed to restore" and we all thought that "it's probably because the package on NuGet is pointing to an older version of CEF" and we did change that and still it is failing.
> 
> I failed on my task so badly I just want to give up.

Its a problem on our Azure infra-structure, still trying to understand what it is.... the error is not clear.

2023-11-23 16:49 UTC, joaompneves commented on CefGlue.Common/CefGlue.Common.csproj
> +        <PackageReference PrivateAssets="None" Include="cef.redist.linux-x64" />
```suggestion
        <PackageReference PrivateAssets="None" Include="cef.redist.linux.x64" />
```

2023-11-23 16:49 UTC, joaompneves commented on CefGlue.CopyLocal.props
> +        <PackageReference Include="cef.redist.linux-x64" />
```suggestion
        <PackageReference Include="cef.redist.linux.x64" />
```

2023-11-23 16:57 UTC, joaompneves commented on Directory.Packages.props
> +        <PackageVersion Include="cef.redist.linux64" Version="$(CefRedistLinuxVersion)" />
```suggestion
        <PackageVersion Include="cef.redist.linux.x64" Version="$(CefRedistLinuxVersion)" />
```

2023-11-23 17:29 UTC, joaompneves commented
Created another [PR](https://github.com/OutSystems/CefGlue/pull/121) with all your commits, and it works. So I guess the problem is that this branch is outside de org. So lets continue there.

2023-11-23 17:29 UTC, closed without merging

2023-11-23 17:29 UTC, Haltroy commented
> > We all thought the reason why checks were failing because "dotnet failed to restore" and we all thought that "it's probably because the package on NuGet is pointing to an older version of CEF" and we did change that and still it is failing.
> > I failed on my task so badly I just want to give up.
> 
> Its a problem on our Azure infra-structure, still trying to understand what it is.... the error is not clear. Nevertheless all the steps you did were necessary. Without the new nuget package version, this would never work.

Do you have access to OutSystems' Azure logs and if they are also not saying anything can you add "-v d" (detailed verbose) to the `dotnet.exe` line? This way you can tell which sub-package or something is failing to download.

Also, this is not longer working on my end and I have no idea why it started doing this. Output:
`[1123/202210.006079:ERROR:icu_util.cc(240)] Invalid file descriptor to ICU data received.`

Google'd it, turns out CefSharp users did also had the same issue for a time caused by files not copying properly. But I did copy the files required by libcef by my own which points to 2 other issues (one dating back when this PR was first opened and I couldn't figure out why):
 - CefGlueBrowserProcess is not copied to the output despite a successful build.
 - NO CEF redist. meaning your package has some issues. Also how did you get that to ~100MB? When I packed the same CEF build with all the required files it is over 300MB.