Linux support (Final)
OutSystems/CefGlue pull request #153
Opened 2024-07-29 09:42 UTC by Haltroy

This is a follow-up for #121, #88 and #119 with help of @kkwpsv

This PR aims to add Linux support on both x64 and ARM64. The x64 support works flawlessly while ARM64 has issues (see below).
Hopefully this is the final last pR on this topic, which is to bring CefGlue to Linux.

This PR also changes README to add a better support table for operating systems (Wİndows, macOS and Linux), UI toolkits (WPF and Avalonia UI) and processor architectures (x64 and ARM64).

Edits by maintainers are allowed on this PR.

Tested on:
 - Arch Linux (x64) - @haltroy
 - Debian 12 (x64) -@kkwpsv
 - [Kylin V10](https://en.wikipedia.org/wiki/Kylin_(operating_system)) (ARM64) - @kkwpsv

## ARM64 Issues (Direct quote from @kkwpsv)

If we load libcef.so dynamic, it will fail with "cannot allocate memory in static TLS block". Maybe CLR uses too much TLS?
I tried glibc.rtld.optional_static_tls . It doesn't work. Maybe my linux os not support it. I don't know how to investigate it further.

Then I tried LD_PRELOAD, it works. But we need to do additional things to make it work with Avalonia. Cef uses HarfBuzz, and Avalonia also uses it. We must set LD_PRELOAD=/path/to/libHarfBuzzSharp.so:/path/to/libcef.so to ensure libHarfBuzzSharp load before cef, or the process will crash with SIGSEGV in HarfBuzz call.

We can also use [patchelf](https://github.com/NixOS/patchelf) to modify the elf file to load cef when process loading.
patchelf --add-needed libHarfBuzzSharp.so --add-needed libcef.so path/to/Xilium.CefGlue.Demo.Avalonia
patchelf --add-needed libcef.so path/to/Xilium.CefGlue.BrowserProcess (Browser process doesn't use Avalonia, so there's no need to add libHarfBuzzSharp.so)

2024-07-29 10:44 UTC, joaompneves requested changes
Nice work. I didn't tested because I don't have Linux, so I'm gonna trust on you :)
Left some comments with suggestions and improvements.
We also need to understand how we will update CefGlue in the future, because now there's a new package dependency.

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Common/BrowserCefApp.cs
> +                    commandLine.AppendSwitch("no-zygote");
add a small comment here to explain why this is needed

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/AvaloniaControl.cs
> +                {
```suggestion
                switch (CefRuntime.Platform)
                {
                    case CefRuntimePlatform.Windows:
                        _hostWindowPlatformHandle = new Window().TryGetPlatformHandle();
                        break;
                    case CefRuntimePlatform.Linux:
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/AvaloniaControl.cs
> +                    // Cef create browser window with CopyFromParent colormap, so the color depth must be same.
```suggestion
                    // Cef creates browser window with CopyFromParent colormap, so the color depth must be same.
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/AvaloniaControl.cs
> +            else if (CefRuntime.Platform == CefRuntimePlatform.Linux)
```
            switch (CefRuntime.Platform)
            {
                case CefRuntimePlatform.Windows:
                    // store cef window handle, to dispose later
                   _browserView = new HostWindow(browserHandle);
                  break;
                case CefRuntimePlatform.Linux:

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +        public static extern int XFlush(IntPtr display);
```suggestion
        private static extern int XDestroyWindow(IntPtr display, IntPtr w);

        [DllImport("libX11.so.6")]
        private static extern IntPtr XOpenDisplay([MarshalAs(UnmanagedType.LPUTF8Str)] string display_name);

        [DllImport("libX11.so.6")]
        private static extern IntPtr XCreateSimpleWindow(IntPtr display, IntPtr parent, int x, int y, uint width, uint height, uint border_width, UIntPtr border, UIntPtr background);

        [DllImport("libX11.so.6")]
        private static extern IntPtr XDefaultRootWindow(IntPtr display);

        [DllImport("libX11.so.6")]
        private static extern int XFlush(IntPtr display);
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +        public IntPtr Handle { get; private set; }
```suggestion
        public IntPtr Handle { get; }
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +        public string HandleDescriptor => "XWindow";
put properties after the constructor

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +        }
do not expose the need dispose param, otherwise it could be misused
```suggestion
        public XWindow(IntPtr handle) : this(handle, false) { }
        
        private XWindow(IntPtr handle, bool needDispose)
        {
            Handle = handle;
            _needDispose = needDispose;
        }
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +            }
trying to avoid concurrency issues on a static field
```suggestion
            var display = _display;
            if (_needDispose && display != IntPtr.Zero)
            {
                XDestroyWindow(display, Handle);
                XFlush(display);
            }
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +            // On Linux, with osr disable, the filename in CefMainArgs will be use as accessible name.
```suggestion
            // On Linux, with osr disable, the filename in CefMainArgs will be used as accessible name.
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +            CefRuntime.Initialize(new CefMainArgs(new[] { exeFileName }), settings, new BrowserCefApp(customSchemes, flags, browserProcessHandler), IntPtr.Zero);
needs to be tested if this doesn't impact the other platforms

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +                // This function set ParentHandle (owner in Windows) and set Bounds to CW_USERDEFAULT (only work in Windows).
```suggestion
                // This function set ParentHandle (owner in Windows) and set Bounds to CW_USERDEFAULT (only works on Windows).
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +            <Visible>true</Visible>
```suggestion
            <Visible>false</Visible>
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +            <Visible>true</Visible>
```suggestion
            <Visible>false</Visible>
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.CopyLocal.props
>      <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
```suggestion
    </PropertyGroup>
    
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.CopyLocal.props
> +        <RuntimeIdentifiers>osx-x64;win-x64;osx-arm64;win-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
```suggestion
        <RuntimeIdentifiers>osx-x64;osx-arm64;win-x64;win-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
```

2024-07-29 10:44 UTC, joaompneves commented on CefGlue.Packages.props
> +        <PackageReference PrivateAssets="None" Include="cef.bin.linux64" />
this package will need to be updated when we update CefGlue, since we dont have control over it, it can be problematic for us to evolve 
```suggestion
        <PackageReference PrivateAssets="None" Include="cef.bin.linux64" />
```

2024-07-29 10:44 UTC, joaompneves commented on README.md
> +
before merging to main this shouldn't be here

2024-07-29 10:44 UTC, joaompneves commented on README.md
> +It can be used from C# or any other CLR language and provides both Avalonia and WPF web browser control implementations. Here's a table for supported architectures, frameworks and operating systems:
```suggestion
It can be used from C# or any other CLR language and provides both Avalonia and WPF web browser control implementations.
Here's a table for supported architectures, frameworks and operating systems:
```

2024-07-29 10:44 UTC, joaompneves commented on README.md
> +| Linux   | ✅   | 🟡    |  ❌ |    ✅    |
although doesn't impact the output, please fix the indentation

2024-07-29 10:44 UTC, joaompneves commented on README.md
> +| Linux   | ✅   | 🟡    |  ❌ |    ✅    |
it could be also useful to say which linux distributions have been tested on and create a new MD page (with a link here) with the explanation of the existing issues

2024-07-29 11:14 UTC, Haltroy commented on README.md
> +
Forgot that line. Removed in commit.

2024-07-29 11:15 UTC, Haltroy commented on CefGlue.Packages.props
> +        <PackageReference PrivateAssets="None" Include="cef.bin.linux64" />
Yes I know that problem. I want to transfer those packages to OutSystems' NuGet and GitHub account. I can do the GitHub one easily but I have no idea how to do the NuGet packages.

2024-07-29 11:29 UTC, Haltroy commented on CefGlue.Common/BrowserCefApp.cs
> +                    commandLine.AppendSwitch("no-zygote");
Usually, we have to disable zygote when we are running CEF without sandbox. But since there's no additional line for disabling the sandbox My guess is that this is a leftover line.

2024-07-29 11:38 UTC, Haltroy commented on README.md
> +| Linux   | ✅   | 🟡    |  ❌ |    ✅    |
Fixed version looks good now, used multiple "markdown prettify" programs to fix it and replaced the emojis too.

2024-07-29 11:39 UTC, Haltroy commented on README.md
> +| Linux   | ✅   | 🟡    |  ❌ |    ✅    |
Added LINUX.md file listing the distributions that are tested with and the ARM64 problem.

2024-07-29 11:54 UTC, Haltroy commented on CefGlue.Common/CefRuntimeLoader.cs
> +            CefRuntime.Initialize(new CefMainArgs(new[] { exeFileName }), settings, new BrowserCefApp(customSchemes, flags, browserProcessHandler), IntPtr.Zero);
I only have Linux installed on my machine so testing on macOS and Windows is out of my league.

2024-07-29 11:57 UTC, Haltroy commented
Fixed most of the requests. Now we need to tackle down 2 issues:
 - There's a line of code that isn't tested on other platforms (macOS and Windows) that needs to be tested and worked on.
 - CEF runtime NuGet packages created by me needs to be handled to OutSystems' account (sent the request).

2024-07-29 12:00 UTC, Haltroy commented on CefGlue.Packages.props
> +        <PackageReference PrivateAssets="None" Include="cef.bin.linux64" />
Sent a request on NuGet. Sending request on GitHub gave me error "You don’t have the permission to create public repositories on OutSystems".

2024-07-29 12:21 UTC, joaompneves commented on CefGlue.Avalonia/Platform/AvaloniaControl.cs
> +                    _hostWindowPlatformHandle = XWindow.CreateHostWindow();
```suggestion
                        // Avalonia window doesn't work. It's color depth is 32.
                        // We should create a x11 window with color depth 24.
                        // Cef creates browser window with CopyFromParent colormap, so the color depth must be same.
                        _hostWindowPlatformHandle = XWindow.CreateHostWindow();
                        break;
```

2024-07-29 12:21 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +         public IntPtr Handle { get; }
```suggestion
        public IntPtr Handle { get; }
```

2024-07-29 12:21 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +
```suggestion
```

2024-07-29 12:21 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +        public XWindow(IntPtr handle) : this(handle, false) { }
```suggestion
        private static IntPtr _display;
        private readonly bool _needDispose;

        public XWindow(IntPtr handle) : this(handle, false) { }
```

2024-07-29 12:21 UTC, joaompneves commented on README.md
> +
```suggestion
```

2024-07-29 12:21 UTC, joaompneves commented on LINUX.md
> +We have not found the işsue why dynamic loading CEF is falinig with "cannot allocate memory in static TLS block" and currently our guess is that CLR uses too much TLS.
```suggestion
We have not found the işsue why dynamic loading CEF is failing with "cannot allocate memory in static TLS block" and currently our guess is that CLR uses too much TLS. 
```

2024-07-29 12:21 UTC, joaompneves commented on LINUX.md
> +Loading CEf with `LD_PRELOAD` environment variable works but need to load HarfBuzzSharp first (`LD_PRELOAD=/path/to/libHarfBuzzSharp.so:/path/to/libcef.so`).
```suggestion
Loading CEf with `LD_PRELOAD` environment variable works but needs to load HarfBuzzSharp first (`LD_PRELOAD=/path/to/libHarfBuzzSharp.so:/path/to/libcef.so`).
```

2024-07-29 12:21 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +using System.Diagnostics;
```suggestion
using System.Diagnostics;
using System.Reflection;
using Xilium.CefGlue.Common.Handlers;
using Xilium.CefGlue.Common.Shared;
```

2024-07-29 12:21 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +using System.Runtime.InteropServices;
```suggestion
using System;
using System.Runtime.InteropServices;
﻿using Avalonia.Controls;
using Avalonia.Platform;
```

2024-07-29 12:25 UTC, joaompneves commented on CefGlue.Avalonia/Platform/Linux/XWindow.cs
> +        private static IntPtr _display;
```suggestion

        private static extern int XFlush(IntPtr display);
        private static IntPtr _display;
```

2024-07-29 12:26 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +            CefRuntime.Initialize(new CefMainArgs(new[] { exeFileName }), settings, new BrowserCefApp(customSchemes, flags, browserProcessHandler), IntPtr.Zero);
let me check on mac and windows

2024-07-29 14:12 UTC, joaompneves commented on CefGlue/CefRuntime.cs
> +                NativeLibrary.TryLoad(libcefs[0], out _);
I'm not comfortable with this change, that will affect Windows and macOS. Whats the intention?

We already have some similar logic that runs on the BrowserProcess:

https://github.com/OutSystems/CefGlue/blob/1a99057788e4d4a02728f8adfd69aafb6237a8dc/CefGlue.BrowserProcess/Helpers/NativeLibsLoader.cs#L10

2024-07-29 14:39 UTC, Haltroy commented on CefGlue/CefRuntime.cs
> +                NativeLibrary.TryLoad(libcefs[0], out _);
That BrowserProcess function gets called later than the CheckVersionByApiHash code. This code requires CEF to be loaded otherwise it simply fails to find CEF in PATH environment variable (its in a complex path on the application folder). This code finds CEF and loads it to memory so the function `libcef.api_hash(0);` can be called to check version. Also we cannot call that code from BrowserProcess without editing the structure of project and these codes do exactly the same thing.
I also though it would be unsafe. [see "marked as resolved" comment](https://github.com/Haltroy/CefGlue/issues/1#issuecomment-1951367408).

2024-07-29 14:58 UTC, joaompneves commented on CefGlue/CefRuntime.cs
> +                NativeLibrary.TryLoad(libcefs[0], out _);
so there are a few concerns here:
1) Windows and macOS work fine without this. We never had issues regarding this, so if this is something required for Linux to work properly it should only run on Linux only.
2) Directory.GetCurrentDirectory() is not correct. You should be looking at AppDomain.CurrentDomain.BaseDirectory- ie the path wree the app binaries are and not the current working dir, otherwise if you run you executable from a different working directory this simply wont work.

2024-07-29 15:39 UTC, joaompneves commented on CefGlue/CefRuntime.cs
> +                throw new NotSupportedException($"Can't find CEF in \"{Directory.GetCurrentDirectory()}\"", dll_ex);
```suggestion
            catch (DllNotFoundException dllEx)
            {
                throw new NotSupportedException($"Can't find CEF in \"{AppDomain.CurrentDomain.BaseDirectory}\"", dllEx);
```

2024-07-29 15:39 UTC, joaompneves commented on CefGlue/CefRuntime.cs
> +                    NativeLibrary.TryLoad(found_libs[0], out _);
EnumerateFiles should be more efficient
```suggestion
                var libCefFile = Directory.EnumerateFiles(AppDomain.CurrentDomain.BaseDirectory, libcef.DllName + ".so", SearchOption.AllDirectories).FirstOrDefault();

                // if found, load the first one.
                if (libCefFile != null)
                    NativeLibrary.TryLoad(libCefFile, out _);
```

2024-07-29 17:29 UTC, joaompneves commented
While trying to produce the cef nuget package for linux, the script is taking alot of time in the stripping phase. In my machine I aborted after 10 mins and in the Azure pipelines (where we will be running the script) it took more than 30mins which finishing. How long is that supposed to take?

2024-07-30 11:45 UTC, Haltroy commented
> While trying to produce the cef nuget package for linux, the script is taking alot of time in the stripping phase. In my machine I aborted after 10 mins and in the Azure pipelines (where we will be running the script) it took more than 30mins without finishing. How long is that supposed to take?
> 
> EDIT: took more than 60mins and the process was aborted with timeout

It shouldn't take that much long. It uses cURL (just like cef.redist.osx) if aria2 was not found. I have no idea where is the issue in, the download phase or the stripping phase. If you have any logs, can you share them here? Also commands "strip" and "aarch64-linux-gnu-strip" are needed. If your machine is not Linux maybe it's trying to strip it for your OS instead?

2024-07-30 13:11 UTC, joaompneves commented
> > While trying to produce the cef nuget package for linux, the script is taking alot of time in the stripping phase. In my machine I aborted after 10 mins and in the Azure pipelines (where we will be running the script) it took more than 30mins without finishing. How long is that supposed to take?
> > EDIT: took more than 60mins and the process was aborted with timeout
> 
> It shouldn't take that much long. It uses cURL (just like cef.redist.osx) if aria2 was not found. I have no idea where is the issue in, the download phase or the stripping phase. If you have any logs, can you share them here? Also commands "strip" and "aarch64-linux-gnu-strip" are needed. If your machine is not Linux maybe it's trying to strip it for your OS instead?
> 
> EDIT: Yes we _**do**_ need to strip these binaries otherwise NuGet won't accept them.

I said in the initial reply, its in the stripping phase. The strip commands don't output anything.

2024-07-30 13:59 UTC, joaompneves commented
This is the Azure log:
Generating script.
Script contents:
sh make_cefredist.sh linux64
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/5825aa49-149a-4e70-85f1-ac0ca844e721.sh
**make_cefredist.sh: 4: [: linux64: unexpected operator**
downloading cef binaries
/usr/bin/aria2c


According to this https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

it should be running on ubuntu 22

2024-07-30 14:38 UTC, Haltroy commented
Tested with the bash version that listed in Ubuntu 22 image packages list. It never gave any errors (also the error on line 4 which was just a check for the first argument and every documentation that I could find is doing it the exact same way)

2024-07-30 14:55 UTC, joaompneves commented
Switching from sh to bash solved.
Although the ARM54 still have some errors:

```
make_cefredist.sh: line 48: aarch64-linux-gnu-strip: command not found
make_cefredist.sh: line 49: aarch64-linux-gnu-strip: command not found
make_cefredist.sh: line 50: aarch64-linux-gnu-strip: command not found
make_cefredist.sh: line 51: aarch64-linux-gnu-strip: command not found
make_cefredist.sh: line 52: aarch64-linux-gnu-strip: command not found
````

Not sure I can I install that in the agent. Is it possible to include that in the script? Can you do that?

2024-07-30 15:23 UTC, Haltroy commented
> Switching from sh to bash solved. Although the ARM54 still have some errors:
> 
> ```
> make_cefredist.sh: line 48: aarch64-linux-gnu-strip: command not found
> make_cefredist.sh: line 49: aarch64-linux-gnu-strip: command not found
> make_cefredist.sh: line 50: aarch64-linux-gnu-strip: command not found
> make_cefredist.sh: line 51: aarch64-linux-gnu-strip: command not found
> make_cefredist.sh: line 52: aarch64-linux-gnu-strip: command not found
> ```
> 
> Not sure I can I install that in the agent. Is it possible to include that in the script? Can you do that?

We need to install [`binutils-aarch64-linux-gnu`](https://packages.ubuntu.com/jammy/binutils-aarch64-linux-gnu) package into that system somehow or run an ARM64 machine (which where normal `strip` command can work its magic). Also ARM64 binaries are way bigger (~2GiB) so we really have to figure out a way. 
Since I have no idea how your Azure systems work, my guess is that running `apt install -y binutils-aarch64-linux-gnu` before executing the bash script is the only way. [This might (?) help](https://stackoverflow.com/a/58002908)

2024-07-30 16:10 UTC, joaompneves reviewed
Update to new package naming

2024-07-30 16:10 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +        <None Condition="'$(CefGlueTargetPlatform)' == 'linux-x64'" Include="@(CefBinLinux64)">
```suggestion
        <None Condition="'$(CefGlueTargetPlatform)' == 'linux-x64'" Include="@(CefRedistLinux64)">
```

2024-07-30 16:10 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +        <None Condition="'$(CefGlueTargetPlatform)' == 'linux-arm64'" Include="@(CefBinLinuxARM64)">
```suggestion
        <None Condition="'$(CefGlueTargetPlatform)' == 'linux-arm64'" Include="@(CefRedistLinuxARM64)">
```

2024-07-30 16:10 UTC, joaompneves commented on CefGlue.Packages.props
> +        <PackageReference PrivateAssets="None" Include="cef.bin.linux64" />
```suggestion
        <PackageReference PrivateAssets="None" Include="cef.redist.linux64" />
```

2024-07-30 16:10 UTC, joaompneves commented on CefGlue.Packages.props
> +        <PackageReference PrivateAssets="None" Include="cef.bin.linuxarm64" />
```suggestion
        <PackageReference PrivateAssets="None" Include="cef.redist.linuxarm64" />
```

2024-07-30 16:10 UTC, joaompneves commented on Directory.Packages.props
> +        <PackageVersion Include="cef.bin.linuxarm64" Version="$(CefRedistLinuxVersion)" />
```suggestion
        <PackageVersion Include="cef.redist.linux64" Version="$(CefRedistLinuxVersion)" />
        <PackageVersion Include="cef.redist.linuxarm64" Version="$(CefRedistLinuxVersion)" />
```

2024-07-30 16:32 UTC, joaompneves reviewed
Fix build

2024-07-30 16:32 UTC, joaompneves commented on CefGlue/CefRuntime.cs
> +﻿using System.IO;
```suggestion
﻿using System.IO;
﻿using System.Linq;
```

2024-07-30 17:04 UTC, joaompneves commented on CefGlue.Common/CefRuntimeLoader.cs
> +            CefRuntime.Initialize(new CefMainArgs(new[] { exeFileName }), settings, new BrowserCefApp(customSchemes, flags, browserProcessHandler), IntPtr.Zero);
Its ok on Windows too

2024-07-30 17:06 UTC, Haltroy commented
So I guess that's it. Nuget & CEF redist issue got solved.

2024-07-30 17:07 UTC, joaompneves commented
Can you test it again on Linux, with the most recent changes?

2024-07-30 17:10 UTC, joaompneves commented
> Can you test it again on Linux, with the most recent changes?

A screenshot would be nice to see how things look on Linux

2024-07-30 17:56 UTC, Haltroy commented
Remember that "no-zygote" line? Yeah it crashed with this error: `[0730/203230.971696:ERROR:zygote_communication_linux.cc(158)] Did not receive ping from zygote child`

I added it back and now everything works.
![0001](https://github.com/user-attachments/assets/309e51d2-bbfb-486b-9cd2-3efd3f3e3b7b)

2024-07-31 08:16 UTC, joaompneves approved these changes

2024-07-31 08:16 UTC, merged

2024-07-31 08:51 UTC, joaompneves commented
Its now available, version: [120.6099.204](https://www.nuget.org/packages/CefGlue.Avalonia/120.6099.204)