RMAC-8115 - Handle exception not observed
OutSystems/CefGlue pull request #21
Opened 2021-09-28 14:37 UTC by heldergoncalves92

JIRA: https://outsystemsrd.atlassian.net/browse/RMAC-8115

2021-09-28 14:38 UTC, heldergoncalves92 commented on CefGlue.Avalonia/CefGlue.Avalonia.csproj
> +    <PackageReference PrivateAssets="all" Include="Avalonia" Version="0.10.7" />
Not needed on fix (just to have a more recent version)

2021-09-28 14:38 UTC, heldergoncalves92 commented on CefGlue.Demo.Avalonia/CefGlue.Demo.Avalonia.csproj
> +    <PackageReference Include="Avalonia.Desktop" Version="0.10.7" />
Same. Not needed

2021-09-28 14:48 UTC, joaompneves commented on CefGlue.Common/JavascriptExecution/JavascriptExecutionEngine.cs
> +                if (e is AggregateException && e.InnerException is TaskCanceledException) {
you should try to create a test for this

2021-09-28 17:08 UTC, joaompneves requested changes

2021-09-28 17:08 UTC, joaompneves commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +        public async Task JavascriptExecutionEngine_DisposeBrowser_ShouldHandleInnerTaskCanceledExceptions()
not a custom scheme test.. its a js test

2021-09-28 17:08 UTC, joaompneves commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +        public async Task JavascriptExecutionEngine_DisposeBrowser_ShouldHandleInnerTaskCanceledExceptions()
please follow the tests naming convention used

2021-09-28 17:08 UTC, joaompneves commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +            var t = Browser.EvaluateJavaScript<string>("function ff(){ let finishDate = new Date((new Date()).getTime() + 10000); let sum = 0; while(new Date() < finishDate) {sum++;} return sum;} ff(
```suggestion
            var t = Browser.EvaluateJavaScript<string>("(() => { const finishTime = new Date().getTime() + 10000; while(new Date().getTime() < finishTime); return 10;})()");
```

2021-09-28 17:08 UTC, joaompneves commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +            var t2 = Task.Run(() => Browser.Dispose());
why do you need a task to run dispose?

2021-09-28 17:08 UTC, joaompneves commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +            Assert.IsNull(exception);
check that the value returned is the default

2021-09-29 10:08 UTC, heldergoncalves92 commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +            var t2 = Task.Run(() => Browser.Dispose());
Not needed after all

2021-09-29 10:09 UTC, heldergoncalves92 commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +            var t = Browser.EvaluateJavaScript<string>("function ff(){ let finishDate = new Date((new Date()).getTime() + 10000); let sum = 0; while(new Date() < finishDate) {sum++;} return sum;} ff(
Done

2021-09-29 10:14 UTC, heldergoncalves92 commented on CefGlue.Tests/CustomSchemes/CustomSchemesTests.cs
> +        }
We already have that test. Check: `CancelledOnTimeout`

2021-09-29 10:30 UTC, joaompneves commented on CefGlue.Tests/Javascript/JavascriptEvaluationTests.cs
> +            Assert.AreEqual(default, result);
```suggestion
            // Arrange
            var evalTask = EvaluateJavascript<int>("const finishTime = new Date().getTime() + 10000; while(new Date().getTime() < finishTime); return 10;");

            // Act
            Browser.Dispose();
            
            try 
            {
                var result = await evalTask;
                Assert.AreEqual(0, result);
            }
            catch (Exception e)
            {
                Assert.Fail(e);
            }
```

2021-09-29 11:30 UTC, joaompneves approved these changes

2021-09-29 11:48 UTC, os-lmo approved these changes

2021-09-29 11:53 UTC, merged