Unsubscribe to events on close and cleanup to release the references
OutSystems/CefGlue pull request #49
Opened 2022-05-06 11:42 UTC by brunocunhasilva

Solve leaks related with a few events that need to be unsubscribed when closing the browser
![image](https://user-images.githubusercontent.com/11468067/167124910-762c7e1e-1a22-4aa3-809a-6269323276a3.png)

2022-05-10 09:51 UTC, joaompneves requested changes

2022-05-10 09:51 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +                _crashServerPipe.MessageReceived -= OnChildProcessCrashed;
looking at the object graph this is being held because the WaitForConnectionAsync (https://github.com/OutSystems/CefGlue/blob/4472/CefGlue.Common.Shared/RendererProcessCommunication/PipeServer.cs#L28) is still running. Once the  _crashServerPipe gets disposed that should go away. Are you sure that you waited long enough for this to be freed?

In case that there's really a problem, clear all the handlers inside  the pipe server instead.

2022-05-10 09:51 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +            }
Also noticed that there's a missing dispose of 
https://github.com/OutSystems/CefGlue/blob/4472/CefGlue.Common.Shared/RendererProcessCommunication/PipeServer.cs#L13

here:
https://github.com/OutSystems/CefGlue/blob/4472/CefGlue.Common.Shared/RendererProcessCommunication/PipeServer.cs#L40

2022-05-10 09:51 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +            Control.SizeChanged -= HandleControlSizeChanged;
whats this for? any real evidence of problems here?... Control is an internal object ... all the references should be kept locally

2022-05-10 13:41 UTC, brunocunhasilva commented on CefGlue.Common/CommonBrowserAdapter.cs
> +                _crashServerPipe.MessageReceived -= OnChildProcessCrashed;
"Once the _crashServerPipe gets disposed that should go away. Are you sure that you waited long enough for this to be freed?"
It's not going away - in one example, I sequentially opened and closed the same module 15 times, which took me more than 15mins to complete, and at the end all of the 15 eSpace references were still being held and 1.25GB of memory  was being used.

"In case that there's really a problem, clear all the handlers inside the pipe server instead."
I don't quite understand how I can clear the handlers inside the PipeServer - I need your insights on this one.

2022-05-11 07:48 UTC, brunocunhasilva commented on CefGlue.Common/CommonBrowserAdapter.cs
> +            Control.SizeChanged -= HandleControlSizeChanged;
After a Zoom chat we decided to remove these event unsubscriptions

2022-05-11 07:50 UTC, brunocunhasilva commented on CefGlue.Common/CommonBrowserAdapter.cs
> +                _crashServerPipe.MessageReceived -= OnChildProcessCrashed;
The MessageReceived handler is now being released in the PipeServer class and not in this one.

2022-05-11 07:53 UTC, brunocunhasilva commented on CefGlue.Common/CommonBrowserAdapter.cs
> +            if (_crashServerPipe != null)
For reference, there's a bug in .NET Core 5 (fixed in .NET Core 6) that happens in Unix systems and that doesn't release the registered NamedPipeServerStreams - "WaitForConnectionAsync does not respond to cancellation"
https://github.com/dotnet/runtime/issues/40289

2022-05-11 07:54 UTC, brunocunhasilva commented on CefGlue.Common.Shared/RendererProcessCommunication/PipeServer.cs
> +            _cancellationTokenSource?.Cancel();
For reference, there's a bug in .NET Core 5 (fixed in .NET Core 6) that happens in Unix systems and that doesn't release the registered NamedPipeServerStreams - "WaitForConnectionAsync does not respond to cancellation"
https://github.com/dotnet/runtime/issues/40289

2022-05-11 08:26 UTC, joaompneves approved these changes

2022-05-18 07:46 UTC, merged