Preserve references in serialization to allow deeper structures to be serialized
OutSystems/CefGlue pull request #54
Opened 2022-09-21 13:26 UTC by brunocunhasilva

- [ ] Preserve references
- [ ] Fix failing tests

2022-09-21 13:49 UTC, joaompneves requested changes
Also needs tests for the JS part of the changes.. which could be inspired on: the NativeObjectInteropTests

2022-09-21 13:49 UTC, joaompneves commented on CefGlue.BrowserProcess/ObjectBinding/JavascriptHelper.cs
> +            "                    delete value.$id;" +
```suggestion
            "                if (value.$id !== undefined) {" +
            "                    const id = value.$id;" +
            "                    delete value.$id;" +
```

2022-09-21 13:49 UTC, joaompneves commented on CefGlue.BrowserProcess/ObjectBinding/JavascriptHelper.cs
> +            "                    }" +
```suggestion
            "                    if (pendingRef) {" +
            "                        value = pendingRef;" +
            "                    } else {" +
            "                        value = {};" +
            "                        pendingRefs.set(refId, value);" +
            "                    }" +
```

2022-09-21 13:49 UTC, joaompneves commented on CefGlue.BrowserProcess/ObjectBinding/JavascriptHelper.cs
> +            "            const pendingRefs = new Map();" +
```suggestion
            "        function revive(name, value, refs, pendingRefs) {" +
```

2022-09-21 13:49 UTC, joaompneves commented on CefGlue.BrowserProcess/ObjectBinding/JavascriptHelper.cs
> +            "            const pendingRefs = new Map();" +
```
            "        function parseResult(result) {" +
            "            const refs = new Map();" +
            "            const pendingRefs = new Map();" +
            "            return isString(result) ? JSON.parse(result, (name, value) => revive(name, value, refs, pendingRefs)) : result;"+
            "        }

2022-09-21 13:49 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +        private const int DeserializerMaxDepth = byte.MaxValue;
theres no connection with byte... so lets use a const
```suggestion
        private const int DeserializerMaxDepth = 255;
```

2022-09-21 13:49 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void HandlesDeepStructuresWithReferenceObjects()
make a test with a single purpose ... reference... not need to test deep structures here.. already done on other tests

2022-09-23 18:11 UTC, joaompneves requested changes
Leave just the cyclic support on the serialization... in this PR

2022-09-23 18:11 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +            ReferenceHandler = _jsonDeserializerReferenceHandler
deserialization does not support references because cef because of this:
https://github.com/OutSystems/CefGlue/blob/4472/CefGlue.BrowserProcess/Serialization/V8ValueSerialization.cs#L24

2022-09-23 18:11 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +            IncludeFields = true,
not needed

2022-09-23 18:11 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +        }
this is very dangerous since its not thread safe and with current system.text.json capabilities its impossible to solve

2022-09-23 18:11 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +        private static JsonSerializerOptions JsonSerializerOptions => _jsonSerializerOptions;
remove

2022-09-23 18:11 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
>      internal class ObjectJsonConverter : JsonConverter<object>
lets not go this path... this has serious thread safety issues... concurrent deserializations will share the same references dictionary... 

to properly support cyclic references on deserialization, we would have to ditch the ObjectJsonConverter (because https://github.com/dotnet/runtime/issues/51715) and do the deserialization by ourselves. that shouldn't be hard to do, but I would put in another separated PR, since it involves some of changes.

2022-09-26 10:07 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
>      internal class ObjectJsonConverter : JsonConverter<object>
What if we have the Deserializer options as threadstatic? (do you foresee problems in this approach)
![image](https://user-images.githubusercontent.com/11468067/192250354-9ab490a6-3a97-41ee-8227-c942902ab6e8.png)

2022-09-26 10:17 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
>      internal class ObjectJsonConverter : JsonConverter<object>
there's no guarantees that the threads are not reused by the thread pool... while performing async work
also creating new json serializer options leads not only to performance issues (because internal caches have to be built from scratch for each instance, and also leads to memory leaks)

2022-09-26 13:07 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
>      internal class ObjectJsonConverter : JsonConverter<object>
I believe that the threads may be reused without any problem, since those threads will only pick up after the initial job has been completed, hence not sharing the references collection, since I can reset it for subsequent uses:
![image](https://user-images.githubusercontent.com/11468067/192283176-e8a55d44-77ac-40e1-bcc7-e089982694a5.png)

![image](https://user-images.githubusercontent.com/11468067/192283827-6a3f3f6e-dc33-4d62-84f4-c8c27bf8c369.png)


As for the potential memory leaks, if I reset the _jsonDeserializerReferenceHandler at the end of the Deserialization process, I don't think we have that problem either:
![image](https://user-images.githubusercontent.com/11468067/192284020-d2e483c7-189a-44a3-b8f9-fb6f54000c6b.png)

We're left with the potential performance issues - can you detail which internal caches are you referring to?

2022-09-27 14:18 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
>      internal class ObjectJsonConverter : JsonConverter<object>
Discarded this approach after aligning with Neves.
A new approach will be followed in a separate PR

2022-09-27 18:33 UTC, joaompneves requested changes
Lots of comments out code... move the commented out code to a new PR so that thus one remains clean

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +using System.Linq;
unused

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Tests/Javascript/NativeObjectInteropTests.cs
> +            Assert.AreEqual(typeof(CyclicObject), result[0].GetType());
Assert.IsInstanceOfType

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Tests/Javascript/NativeObjectInteropTests.cs
> +            Assert.NotNull(arg.Child.Parent);
missing the reference equality check

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        private static object SerializeAndDeserialize<T>(object value, out CefValueType valueType, DeserializationType deserializationType = DeserializationType.CefValue)
```suggestion

        private static object SerializeAndDeserialize<T>(object value, out CefValueType valueType, DeserializationType deserializationType = DeserializationType.CefValue)
```

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        private class Person
move to the top

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            AssertSerialization<List<string>>(list, CefValueType.String, DeserializationType.Standard);
needs generics to be explicitly passed?

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void HandlesDeserializationOfDeepListsWith248LevelsWithoutReferences()
whats this case for? how is this different from the one above?

2022-09-27 18:33 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void HandlesReferenceObjects()
HandlesCyclicObjectReferences covers this

2022-09-28 14:13 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void Handles100ParallelTasksOfCyclicObjectReferences()
shouldn't we keep it to avoid anyone, in the future, introducing state that may break multi-threaded serialization?

2022-09-28 14:18 UTC, brunocunhasilva commented on CefGlue.Tests/Javascript/NativeObjectInteropTests.cs
> +            Assert.NotNull(arg.Child.Parent);
Considering that the JS still doesn't serialize the objects with $id, $ref properties, the equality check can't currently be done.

2022-09-28 14:23 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            AssertSerialization<List<string>>(list, CefValueType.String, DeserializationType.Standard);
Yes - otherwise the resulting type won't be the same - it'll be an array

2022-09-28 14:24 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void HandlesDeserializationOfDeepListsWith248LevelsWithoutReferences()
This one specifically tests the DeserializeCefValue, while the above one tests the Serialize only.

2022-09-28 14:35 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            AssertSerialization<List<string>>(list, CefValueType.String, DeserializationType.Standard);
Yes, otherwise the obtained type will be an array and won't match the original type.

2022-09-28 15:37 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void Handles100ParallelTasksOfCyclicObjectReferences()
nah... there might be ways to break taht that this test wont cover.. and also multi-threading tests are always unpredictable

2022-09-28 15:37 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        }
useless method

2022-09-28 15:37 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void HandlesDeserializationOfDeepListsWith248LevelsWithoutReferences()
why 248?

2022-09-28 15:37 UTC, joaompneves commented on CefGlue.Tests/Serialization/StringJsonConverter.cs
> +    internal class StringJsonConverter : JsonConverter<string>
this is temporary?

2022-09-29 09:24 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        public void HandlesDeserializationOfDeepListsWith248LevelsWithoutReferences()
It was a left over from the changes done to ObjectJsonSerializer that were able to handle 248 levels. I'll change to 250, to match the Serializer test.

2022-09-29 09:27 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        }
I'll leave it, because it'll make it easier to refactor the tests in the [#55](https://github.com/OutSystems/CefGlue/pull/55) PR, since the method with the Generic won't be needed anymore.

2022-09-29 09:32 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/StringJsonConverter.cs
> +    internal class StringJsonConverter : JsonConverter<string>
Yes - it won't be needed when the [#55 PR](https://github.com/OutSystems/CefGlue/pull/55) is complete.

2022-09-30 15:42 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            Assert.IsTrue(cefValue.GetString().TrimEnd('}', ']').EndsWith("\"$ref\":\"2\""), "The last element in the list should be a reference to the first child");
just a note... when deserialization comes in these tests should stop comparing strings

2022-09-30 15:46 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +        }
its not used

2022-09-30 15:46 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            Assert.DoesNotThrow(() => obtainedValue = SerializeAndDeserialize<Dictionary<string, object>>(dict, out var _, DeserializationType.Standard));
```suggestion
            Assert.DoesNotThrow(() => obtainedValue = SerializeAndDeserialize(dict, out var _, DeserializationType.Standard));
```

2022-09-30 15:46 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            Assert.DoesNotThrow(() => obtainedValue = SerializeAndDeserialize<List<object>>(list, out var _, DeserializationType.Standard));
```suggestion
            Assert.DoesNotThrow(() => obtainedValue = SerializeAndDeserialize(list, out var _, DeserializationType.Standard));
```

2022-09-30 15:46 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            Assert.DoesNotThrow(() => obtainedValue = SerializeAndDeserialize<Person>(parent, out var _, DeserializationType.Standard));
```suggestion
            Assert.DoesNotThrow(() => obtainedValue = SerializeAndDeserialize(parent, out var _, DeserializationType.Standard));
```

2022-09-30 16:17 UTC, merged