Preserve references in deserialization
OutSystems/CefGlue pull request #55
Opened 2022-09-28 14:02 UTC by brunocunhasilva

- [ ] Replace ObjectJsonConverter
- [ ] Add logic to preserve references
- [ ] Support references in JS serialization
- [ ] Refactor tests

2022-09-30 17:42 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
change also https://github.com/OutSystems/CefGlue/pull/55/files#diff-519d5dbffd5b99ec72bc636a0577d3d58bfe8139ef3de35539c2276fd4e2c53bR319

2022-09-30 17:42 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
>              AssertSerialization(new string[0], CefValueType.String);
also check the return type of the deserialized object... should be an array

2022-09-30 17:42 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            AssertSerialization(new List<string>(), CefValueType.String);
also check the return type of the deserialized object... should be an array

2022-09-30 17:42 UTC, joaompneves commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            Assert.AreSame(obtainedValue,
ToArray ... that wont work...it will never be the same reference

2022-10-04 17:25 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +        private int GetArraySize(Utf8JsonReader reader)
Code was refactored to be simpler

2022-10-13 17:16 UTC, joaompneves requested changes

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            while (reader.CurrentDepth > startDepth || reader.TokenType != JsonTokenType.EndArray)
I think it reads better because the stop condition is when the current depth == start and we found the endarray token
```suggestion
            while (!(reader.CurrentDepth == startDepth && reader.TokenType == JsonTokenType.EndArray))
```

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                    && reader.TokenType != JsonTokenType.PropertyName
not needed ... that would be malformed json

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonReaderExtensions.cs
> +public static class JsonReaderExtensions
are you using all these extension methods?

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonReaderExtensions.cs
> +namespace Xilium.CefGlue.Common.Shared.Serialization;
file formmating not compliant with cefglue

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common/Helpers/JavascriptToNativeTypeConverter.cs
> +        public static object ConvertToNative(object obj, Type expectedType, Dictionary<object, object> convertedObjectsMap)
```suggestion
        public static object ConvertToNative(object obj, Type expectedType, IDictionary<object, object> convertedObjectsMap)
```

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common/Helpers/JavascriptToNativeTypeConverter.cs
> +        public static object ConvertToNative(object obj, Type expectedType, Dictionary<object, object> convertedObjectsMap)
needs to be public?

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common/Helpers/JavascriptToNativeTypeConverter.cs
> +        private static object ConvertToNativeObject(object obj, Type expectedType, Dictionary<object, object> convertedObjectsMap)
```suggestion
        private static object ConvertToNativeObject(object obj, Type expectedType, IDictionary<object, object> convertedObjectsMap)
```

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common/Helpers/JavascriptToNativeTypeConverter.cs
>                  return ConvertToNativeList(obj, expectedType);
what about lists?

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +        private int PeekAndCalculateArraySize(Utf8JsonReader reader)
this should go to the json extensions

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            reader.Read(); // PropertyName
replace with read tokens

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            public int? ArrayIndex;
should be props

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            public ReadState(string propertyName, int? arrayIndex, bool hasReference, object objectHolder)
doesnt make sense to have all these params simultaneously in a single ctor

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            public readonly bool HasReference;
whats this for?

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        continue;
these cases should no longer be applicable

2022-10-13 17:16 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +        private bool HandleReferences(ref Utf8JsonReader reader, Dictionary<string, object> referencesMap, out object value, out bool isNewArray)
this method logic is confusing..

2022-11-02 15:33 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            Assert.AreSame(obtainedValue,
It's not comparing the ToArray instances, but the specific array elements inside of the array. And they are the same instance.

2022-11-02 15:37 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
Didn't understand what you're suggesting here.

2022-11-02 18:15 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        continue;
They still are, because the RendererProcessCommunication still deserializes plain arrays, such as it happens here:
https://github.com/OutSystems/CefGlue/blob/adcb6d5557d9134e4041032f50fe0341f1a8ef72/CefGlue.Common.Shared/RendererProcessCommunication/Messages.cs#L109

Moreover, not supporting this would make us over-engineer the SerializationTests, so that we could validate the object[] serializations without using the deserializer.

2022-11-02 18:17 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +        private bool HandleReferences(ref Utf8JsonReader reader, Dictionary<string, object> referencesMap, out object value, out bool isNewArray)
Let's have a zoom chat and discuss how we can improve this

2022-11-03 09:45 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        value = reader.TryGetInt64(out var number)
Using the GetNumber instead of Read, as we would lose readability in the cycle.

2022-11-03 09:46 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        var stringValue = reader.GetString();
Same as for GetNumber

2022-11-03 11:02 UTC, brunocunhasilva commented on CefGlue.Tests/Serialization/CefValueSerializationTests.cs
> +            AssertSerialization(new List<string>(), CefValueType.String);
being done inside of the AssertSerialization method, by converting the passed list to an array and comparing it with the deserialize result:
![image](https://user-images.githubusercontent.com/11468067/199704600-fbc63830-c402-4eca-84de-f9a12e89f9ab.png)

2022-11-03 12:11 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefReferencesResolver.cs
> +                var key = ObjectToReferenceIdMap.Keys.FirstOrDefault(k => _equalityComparer.Equals(k, value));
This is how I was able to solve the problem of searching for the CefV8Values in the map, considering that equal V8CefValues may have different HashCodes. Can you suggest a better approach?

2022-11-03 13:31 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +        public static object DeserializeCefValue(CefValueWrapper cefValue, IReferencesResolver<object> referencesResolver)
This was already `public`, but yes, it can be reduced to `internal`

2022-11-03 13:57 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
>                          }
Created an extension for this - `GetObjectFromString`

2022-11-03 14:08 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            while (reader.CurrentDepth > startDepth || reader.TokenType != JsonTokenType.EndArray)
I actually find it harder to understand as it's a negation of a multiple steps condition. The current resolves in a simpler way in my mid:
Continue if condition 1 is true or condition 2 is true

2022-11-03 15:01 UTC, brunocunhasilva commented on CefGlue.Common/Helpers/JavascriptToNativeTypeConverter.cs
>                  return ConvertToNativeList(obj, expectedType);
Didn't understand what you mean

2022-11-03 15:54 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            public ReadState(string propertyName, int? arrayIndex, bool hasReference, object objectHolder)
I can only remove the propertyName from the constructor, considering it's not being used

2022-11-03 15:55 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +            public readonly bool HasReference;
This is needed to distinguish from arrays with reference id - `$id=N,$values=[...]` from plain arrays [].

2022-11-18 19:01 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        }
```suggestion
                        stateStack.Pop();
```

2022-11-18 19:07 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +
private static readonly ReadState ListWrapperMarker = new ReadState();

2022-11-23 14:57 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +                        return DeserializeCefList<object>(cefList, referencesResolver);
We need to pass the resolver here, because the List may appear nested inside a other dictionaries - if we don't pass the referencesResolver, the list owner dictionary references can't be resoved

2022-11-23 16:29 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +        private Lazy<Dictionary<T, string>> _lazyObjectToReferenceIdMap;
Wasn't this what you intended by [this](https://github.com/OutSystems/CefGlue/pull/55#discussion_r994811965) comment?

2022-11-24 09:12 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +                        return DeserializeCefList<object>(cefList, referencesResolver);
yeah... but like I said then the list also needs to be registered

2022-11-24 09:17 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +        private Lazy<Dictionary<T, string>> _lazyObjectToReferenceIdMap;
yes, but only the _lazyObjectToReferenceIdMap would justify taht... either way i don't think that  the overhead justifies... I would create the dictionaries right away

2022-11-24 11:36 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +        private class ReadState
We can't make full use of the record keyword, because CefGlue still targets .net472, and we get compiler errors when using certain patterns.
Check the answer in this [thread](https://developercommunity.visualstudio.com/t/error-cs0518-predefined-type-systemruntimecompiler/1244809)

2022-11-24 13:54 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +                        return DeserializeCefList<object>(cefList, referencesResolver);
No - the list doesn't have a reference id - only the dictionaries (that correspond to objects) need to be registered.

2022-11-24 13:55 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +        internal static TListElementType[] DeserializeCefList<TListElementType>(ICefListValue cefList, IReferencesResolver<object> referencesResolver = null)
https://github.com/OutSystems/CefGlue/pull/55/files#r1030546677

2022-11-24 14:31 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        if (!HandleReferences(ref reader, referencesMap, out value, out var isNewArray))
Had to do some changes to the proposed approach, to work as expected.

2022-11-24 14:57 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +        {
Had to do some changes to the proposed approach, so it works as expected.

2022-11-24 15:01 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +        private Lazy<Dictionary<T, string>> _lazyObjectToReferenceIdMap;
I tend to disagree because there are many serializations&deserializations that don't require object references. Having the collections initialized for every serialization&deserialization will have some memory overhead that shouldn't be neglected.

2022-11-24 15:11 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        obj ??= new Dictionary<string, object>();
```suggestion
                        }
                        else 
                        {
                            obj = new Dictionary<string, object>();
                        }
```

2022-11-24 15:11 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        var id = tempReader.ReadString();
i guess its the reader here, at leats its not consistent with the branch above
```suggestion
                        var id = reader.ReadString();
```

2022-11-24 15:19 UTC, joaompneves commented on CefGlue.BrowserProcess/Serialization/CefV8ValueEqualityComparer.cs
> +            return obj.GetHashCode();
this gives you the hashcode for the .net object... i think that this wont work as intended

2022-11-24 15:19 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +                var key = ObjectToReferenceIdMap.Keys.FirstOrDefault(k => _equalityComparer.Equals(k, value));
we need to investigate this further. this can be very ineficient. probably a live debugging session to see some other alternatives would help

2022-11-24 15:25 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +        private Lazy<Dictionary<T, string>> _lazyObjectToReferenceIdMap;
ok, but in that case create a dummy implementation of IReferencesResolver that is basically a placebo

2022-11-24 15:44 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        var id = tempReader.ReadString();
It can't be the reader, because we're peeking for the $values property - if it's not, we can't consume that reader position, because it will be consumed in the while cycle continuation.

2022-11-24 15:47 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        var id = tempReader.ReadString();
but something is not right, the branch above doesn't do the same... and they should be consistent because the scenario is very similar

2022-11-24 15:57 UTC, brunocunhasilva commented on CefGlue.BrowserProcess/Serialization/CefV8ValueEqualityComparer.cs
> +            return obj.GetHashCode();
It returns the value for the reference object and not a calculated value of the ValueObject, which is what would be ideal - but I simply don't know how to do it.

2022-11-25 16:29 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +        private Lazy<Dictionary<T, string>> _lazyObjectToReferenceIdMap;
Not possible, because you can't foresee if a regular implementation of IReferencesResolver will be needed or not. Only when you go through the deserialization process you are able to detect if the references resolver is needed or not. That's why we're instantiating it at this moment:
![image](https://user-images.githubusercontent.com/11468067/204025549-b9537569-4321-4113-86f7-906d31d0ca1f.png)

2022-11-25 17:11 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +        public static object DeserializeCefValue(CefValueWrapper cefValue, IReferencesResolver<object> referencesResolver = null)
This way, we'll always instantiate a referencesResolver, even when it's not needed - like it's the case of arrays of value types.
Do you think the null check will have a relevant performance impact?

2022-11-25 17:24 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonConverters/ObjectJsonConverter.cs
> +                        var id = tempReader.ReadString();
Not exactly the same as the branch above, because that branch uses the `reader.GetString()`, which doesn't consume the position. And if I were to use the `reader.GetString()`, I'd be forced to add another line just to consume that position in the tempReader so I could read the following PropertyName, to check if it's $values.

2022-11-25 17:36 UTC, brunocunhasilva commented on CefGlue.Common/Helpers/JavascriptToNativeTypeConverter.cs
>                  return ConvertToNativeList(obj, expectedType);
Got it. Added a couple of tests and corrected the code.

2022-11-25 17:38 UTC, brunocunhasilva commented on CefGlue.Common.Shared/CefGlue.Common.Shared.csproj
> +    <LangVersion>latest</LangVersion>
Wasn't able to. Doing that move from the csproj to the Directory.Build.props led to compilation errors.

2022-11-28 14:08 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefValueSerialization.cs
> +        public static object DeserializeCefValue(CefValueWrapper cefValue, IReferencesResolver<object> referencesResolver = null)
I ended up splitting the method into an `internal` (that doesn't expose the `referencesResolver`) and a `private` one that receives the `referencesResolver` argument

2022-11-28 15:53 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +                var key = ObjectToReferenceIdMap.Keys.FirstOrDefault(k => _equalityComparer.Equals(k, value));
Currently, the code already suffers from this inefficiency, in a more impactful way, considering that it always compares the V8Values in every serialization:
https://github.com/OutSystems/CefGlue/blob/e635050bfd356e8d80e3c2566fe0ff3018621858/CefGlue.BrowserProcess/Serialization/V8ValueSerialization.cs#L22

In this PR we're removing that check and reducing the comparisons that are made.

2022-11-28 16:17 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +                var key = ObjectToReferenceIdMap.Keys.FirstOrDefault(k => _equalityComparer.Equals(k, value));
but it only compares a few objects (many as the nesting level)

2022-12-19 09:57 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/CefReferencesResolver.cs
> +                var key = ObjectToReferenceIdMap.Keys.FirstOrDefault(k => _equalityComparer.Equals(k, value));
This approach was removed. Closing the comment

2022-12-19 09:59 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/ReferencesResolver.cs
> +                var key = ObjectToReferenceIdMap.Keys.FirstOrDefault(k => _equalityComparer.Equals(k, value));
The new implemented solution no longer uses this approach. Closing this conversation

2022-12-19 10:03 UTC, brunocunhasilva commented on CefGlue.BrowserProcess/Serialization/CefV8ValueEqualityComparer.cs
> +            return obj.GetHashCode();
The new solution no longer uses this comparer. Closing this conversation

2022-12-20 12:42 UTC, joaompneves reviewed
not finished reviewing but there's already alot of stuff to address

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common/InternalHandlers/CommonCefRenderHandler.cs
> +                _logger.Debug($"TypeInfo: {type} Buffer: {buffer.ToInt64()} Width: {width} Height: {height}");
intended?

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/State/TypeMethodInfo.cs
> +    internal record TypeMethodInfo
records should be pure DTOs
```suggestion
    internal class TypeMethodInfo
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        private const int DeserializerMaxDepth = byte.MaxValue * 2;
maxdepth can be the max value allowed... we no longer depend on the framework recursion limits

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +            }
```suggestion
                            if (jsonString == null)
                {
                    return default(TargetType);
                }

            try
            {
                return (TargetType)Deserialize(jsonString, typeof(TargetType), parametersTypes);
            }
            catch (JsonException e)
            {
                // wrap the json exception
                throw new InvalidOperationException(e.Message);
            }
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        private static object Deserialize(string jsonString, Type typeToConvert, ParametersTypes parametersTypes = null)
```suggestion
        private static T InnerDeserialize<T>(string jsonString, ParametersTypes parametersTypes = null)
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        private static object Deserialize(ref Utf8JsonReader reader, Type typeToConvert, ParametersTypes parametersTypes = null)
```suggestion
        private static T Deserialize<T>(ref Utf8JsonReader reader, ParametersTypes parametersTypes = null)
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +            byte[] bytes = Encoding.UTF8.GetBytes(jsonString);
```suggestion
            var bytes = Encoding.UTF8.GetBytes(jsonString);
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                            );
it makes more sense to use like this
```suggestion
                        currentState.SetValue(reader.GetNumber(currentState.GetPropertyType());
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                obj = new object();
hum.. you would be pushing null to the current state, is that ok? have a test that falls into this case?

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                    case JsonAttributes.Ref:
missing here a comment with a json snippet of the expected json that will be read

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                        newState = CreateNewDeserializerState(obj, newTypeInfo);
```suggestion
                        newState = CreateNewDeserializerState(refInfo.Object, refInfo.TypeInfo);
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                        if (propName == JsonAttributes.Values)
avoid reusing variables
```suggestion
                        if (tempReader.ReadPropertyName() == JsonAttributes.Values)
```

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +            JsonTypeInfo newTypeInfo = null;
only the newState is necessary... the other vars are for local scopes... declare them inplace where needed

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        public static TargetType Deserialize<TargetType>(string jsonString, ParametersTypes parametersTypes = null)
work with type info abstraction and remove parameter types all over

2022-12-20 12:42 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        private static IDeserializerState CreateNewDeserializerState(
hum.. all these CreateNewDeserializerState seem a little complicated... I believe theres room for simplification

2022-12-21 10:09 UTC, brunocunhasilva commented on CefGlue.BrowserProcess/ObjectBinding/CefGlueGlobalScript.js
> +                }
Please check the changes to this commit - I have doubts about the identification of a binary value (checking if it's an instance of Uint8Array).
![image](https://user-images.githubusercontent.com/11468067/208879294-12c9f7d6-de70-4120-84ae-86d9e969625d.png)

2023-01-31 15:06 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/JsonReaderExtensions.cs
> +                    return Convert.ChangeType(reader.GetDouble(), typeToConvert);
Yes - for example, check the `JavascriptEvaluationTests.DynamicObjectReturn` test.
That's why I left the comment

2023-01-31 15:47 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        private const int DeserializerMaxDepth = byte.MaxValue * 2;
There's seems to exist a limitation in the JsonSerializer that throws an exception when serializing objects deeper than 1000 levels - this was causing an error in some tests I did, which ended up with me setting a lower value. But I guess our code should not be concerned by this internal limitation of the JsonSerializer, one that can be changed in future versions.
![image](https://user-images.githubusercontent.com/11468067/215807839-54d7b216-ebf8-4463-b516-580ab8e531f7.png)


I'll set this maxDepth to be `int.MaxValue`

2023-01-31 17:38 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        public static TargetType Deserialize<TargetType>(string jsonString, ParametersTypes parametersTypes = null)
What type info abstraction are you referring to? (When deserializing an argumentsArray string, it's TargetType will be `object[]`, but we need to deserialize each one of its elements to the correct argument type)

Can you be a bit more specific?

2023-01-31 17:59 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +            JsonTypeInfo newTypeInfo = null;
Only the `newTypeInfo` variable can be moved, the other variables are used within the current scope.

2023-02-01 10:20 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                obj = new object();
Nice catch. I had forgotten to create a test that validated plain objects (e.g. `new object()`).
I created one and fixed this part of the code.

2023-02-01 16:07 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        private static IDeserializerState CreateNewDeserializerState(
Refactored the code a bit.

2023-02-01 16:27 UTC, brunocunhasilva commented on CefGlue.BrowserProcess/Handlers/RenderProcessHandler.cs
> +            JavascriptHelper.RegisterJavascriptExecution(_messageDispatcher);
I don't understand what you mean

2023-02-06 19:47 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        public static TargetType Deserialize<TargetType>(string jsonString, ParametersTypes parametersTypes = null)
Check the changes made in [this commit](https://github.com/OutSystems/CefGlue/pull/55/commits/f3eacc2d3b7b4ec79b54ba360b0bcba2d08ccfb0).
The code is not as resource efficient as it was, but it complies with the responsibilities isolation, namely in the Deserializer not knowing what ParameterTypes are and their specifics.

2023-02-07 10:29 UTC, joaompneves commented on CefGlue.Common/ObjectBinding/NativeMethod.cs
>              var convertedArgs = new List<object>(_mandatoryParameters.Length + 1);
we should create and array here right away with the final size... to avoid and extra allocation

2023-02-07 10:29 UTC, joaompneves commented on CefGlue.Common/ObjectBinding/NativeMethod.cs
> +        private object[] ConvertToNative(string args)
InnerConvertArguments

2023-02-07 10:29 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +        private static object Deserialize(ref Utf8JsonReader reader, Type[] targetTypes)
```suggestion
        private static object InnerDeserialize(ref Utf8JsonReader reader, Type[] targetTypes)
```

2023-02-07 10:29 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +            state.Push(new ArrayDeserializerState(root, targetTypes[0]));
why just the first targetType?

2023-02-07 10:29 UTC, joaompneves commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                        var isRootObjectHolder = currentState.ObjectHolder == root;
why is root a special case? something is not right

2023-02-07 10:29 UTC, joaompneves commented on CefGlue.Common/ObjectBinding/NativeMethod.cs
> +                targetTypes = targetTypes.Append(optionalParameterElementType);
why the element type and not the the paramType?

Deserializer should receive information that you want an array of X type, that way the hack below wouldn't also be needed

2023-02-07 12:08 UTC, brunocunhasilva commented on CefGlue.BrowserProcess/ObjectBinding/CefGlueGlobalScript.js
> +        }
Not quite, because the test `JavascriptEvaluationTests.BinaryReturn` if I use the `btoa(byteArray)` here

2023-02-07 13:46 UTC, brunocunhasilva commented on CefGlue.Common/ObjectBinding/NativeMethod.cs
> +                targetTypes = targetTypes.Append(optionalParameterElementType);
The problem lies with the jsonString itelf, which is not an array for the optional parameters.
Arguments are in the form of an array, but the optional ones are not a sub-array.
e.g. this is an example of what the json string looks like:
"[arg1, arg2, optionalArg1, optionalArg2]"

To work as you are asking, the string would have to be in the form of:
"[arg1, arg2, [optionalArg1, optionalArg2]]"

2023-02-08 09:03 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/Deserializer.cs
> +                        var isRootObjectHolder = currentState.ObjectHolder == root;
It was a way of distinguishing between the root `ArrayDeserializerState` and the `ArrayDeserializerState` that is used for the "arguments" array (in https://github.com/OutSystems/CefGlue/blob/53baca0223c77d6f7f91a4c99073021db31e054d/CefGlue.Common.Shared/Serialization/Deserializer.cs#L249)

Nevertheless, I ended up refactoring the code and removing the need to check for the isRootObjectHolder

2023-02-08 10:58 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/State/JsonTypeInfo.cs
> +        public Dictionary<string, TypeMemberInfo> TypeMembers { get; } = new Dictionary<string, TypeMemberInfo>();
If it becomes a IReaOnlyDictionary, than the Add of elements can't be done in `JsonTypeInfoCache`, as it is now. And an `AddTypeMember` method must be created inside of the `JsonTypeInfo` class (switched from Record to class considering it'll have some login inside)

2023-02-08 11:58 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/State/ArrayDeserializerState.cs
> +                );
What syntax are you referring to? (the way the method is split, the usage of a ternary expression, not using the explicit get)?

2023-02-09 16:43 UTC, brunocunhasilva commented on CefGlue.Common.Shared/Serialization/State/JsonTypeInfo.cs
> +            }
refactored

2023-02-16 21:35 UTC, closed without merging