Add RequestCentext assessor
OutSystems/CefGlue pull request #74
Opened 2023-02-17 15:00 UTC by Wiks00

Hello.
Would like to introduce functionality to add a request context to the browser creation process.

2023-02-17 15:03 UTC, Wiks00 commented
> Hello @Wiks00 👋
> 
> Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the 📝 [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
> 
> After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

I read, understood and accept the OutSystems CLA

2023-02-21 10:33 UTC, Wiks00 commented
@joaompneves, @dmitry-azaraev Could anyone take a look ?
Thanks.

2023-02-23 17:54 UTC, dmitry-azaraev commented
> @dmitry-azaraev Could anyone take a look ? Thanks.

I'm not an owner of this repository, nor functionality of changed codepaths. CefGlue lives only in https://gitlab.com/xiliumhq/chromiumembedded/cefglue and actually i'm care only about `Xilium.CefGlue` assembly. Everything else is out of my scope.

2023-02-23 18:01 UTC, dmitry-azaraev commented on CefGlue.Common/BaseCefBrowser.cs
> +            get
code style: code around prefers more shorter/lambda forms.

2023-02-24 11:15 UTC, joaompneves requested changes
Thank you for your contribution. I left some suggestions to improve the solution.

2023-02-24 11:15 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
```suggestion
        public CefRequestContext RequestContext { 
            get => _adapter.RequestContext;
            init => _adapter.RequestContext = value;
        }
```

2023-02-24 11:15 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +        public CefRequestContext RequestContext { get; set; }
```suggestion
        public CefRequestContext RequestContext { get; init; }
```

2023-02-24 11:15 UTC, joaompneves commented on CefGlue.Demo.Avalonia/BrowserView.xaml.cs
> +            browser.RequestContext = CefRequestContext.CreateContext(new CefRequestContextSettings(), null);
create a unit test for this functionality instead

2023-02-24 14:01 UTC, Wiks00 commented on CefGlue.Common/CommonBrowserAdapter.cs
> +        public CefRequestContext RequestContext { get; set; }
Good point. Moved initialization to ctor

2023-02-24 14:53 UTC, Wiks00 commented
> > @dmitry-azaraev Could anyone take a look ? Thanks.
> 
> I'm not an owner of this repository, nor functionality of changed codepaths. CefGlue lives only in https://gitlab.com/xiliumhq/chromiumembedded/cefglue and actually i'm care only about `Xilium.CefGlue` assembly. Everything else is out of my scope.


Got it, sorry for the confusion. 
Anyway thanks for reply.

2023-02-27 10:38 UTC, Wiks00 commented on CefGlue.Demo.Avalonia/BrowserView.xaml.cs
> +            browser.RequestContext = CefRequestContext.CreateContext(new CefRequestContextSettings(), null);
Done

2023-02-27 10:58 UTC, joaompneves requested changes

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
please revert this change... the browser should only be loaded upon the first browser instantiation, not when you use the browser class for the first time... stick with the minimal changes needed for the PR

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +        public CefRequestContext RequestContext { get; init; }
```suggestion
        public CefRequestContext RequestContext { get; }
```

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +        { }
drop this overload... lets keep this simple

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Avalonia/AvaloniaCefBrowser.cs
> +        public AvaloniaCefBrowser(CefRequestContextSettings cefRequestContextSettings, CefRequestContextHandler cefRequestContextHandler = null)
```suggestion
        public AvaloniaCefBrowser(CefRequestContext cefRequestContext)
```

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Avalonia/AvaloniaCefBrowser.cs
> +        { }
```suggestion
        public AvaloniaCefBrowser() : base(null) { }
```

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Tests/TestBase.cs
> +            browser?.Dispose();
is this change needed?

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Tests/TestBase.cs
> +                window?.Close();
needed?

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +        class CustomCefRequestContextHandler : CefRequestContextHandler
```suggestion
        private class CustomCefRequestContextHandler : CefRequestContextHandler
```

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +            var cachePath = @"C:/path/to/cache";
```suggestion
            const string CachePath = @"C:/path/to/cache";
```

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +            var browser = () => new AvaloniaCefBrowser(new CefRequestContextSettings());
```suggestion
            var browserFactory = () => new AvaloniaCefBrowser(new CefRequestContextSettings());
```

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +            var browser = () => new AvaloniaCefBrowser(new CefRequestContextSettings()
```suggestion
            var browserFactory = () => new AvaloniaCefBrowser(new CefRequestContextSettings()
```

2023-02-27 10:58 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +            var browser = () => new AvaloniaCefBrowser(new CefRequestContextSettings(), customRequestContextHandler);
```suggestion
            var browserFactory = () => new AvaloniaCefBrowser(new CefRequestContextSettings(), customRequestContextHandler);
```

2023-02-27 11:16 UTC, Wiks00 commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
But does this piece of code represent browser initialization? In essence, the logic has not been changed. 
It is also impossible to create a RequestContext without first calling this block of code, which prevents the initialization of the RequestContext instance outside of this class.

2023-02-27 11:18 UTC, Wiks00 commented on CefGlue.Common/BaseCefBrowser.cs
> +        { }
Please see my comment about static ctor.

2023-02-27 11:23 UTC, Wiks00 commented on CefGlue.Tests/TestBase.cs
> +            browser?.Dispose();
Yes, because if the test fails before running the `SetUp `code (in the case of RequestContext `InternalSetup`), this part of the test will crash.

2023-02-27 11:29 UTC, Wiks00 commented on CefGlue.Avalonia/AvaloniaCefBrowser.cs
> +        public AvaloniaCefBrowser(CefRequestContextSettings cefRequestContextSettings, CefRequestContextHandler cefRequestContextHandler = null)
Also closely related to browser initialization.

2023-02-27 11:55 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +        public async Task CustomCefReqestContextHandlerApplied()
```suggestion
        public async Task CustomCefRequestContextHandlerApplied()
```

2023-02-27 11:55 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +        public async Task CefReqestContextApplied()
```suggestion
        public async Task CefRequestContextApplied()
```

2023-02-27 11:55 UTC, joaompneves commented on CefGlue.Tests/RequestContext/CustomRequestContext.cs
> +        public async Task NotGlobalCefReqestContext()
```suggestion
        public async Task NonGlobalCefRequestContext()
```

2023-02-27 11:55 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
This piece of code basically loads cef dlls. I see what you're saying... but I'm also not very comfortable with this change because Load must be called on the main thread (typically the ui thread)... and with this change one can accidentally not call it on other threads

2023-02-27 12:14 UTC, Wiks00 commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
Based [on documentation](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors#remarks) this is safe.
If the `BaseCefBrowser` instance is initialized on the UI thread, then the static ctor will run on the same thread.

2023-02-27 15:24 UTC, Wiks00 commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
Sorry, but I did not quite understand your point in the example.
The `typeof `operator takes the` System.Type` instance for the type and has nothing to do with `AvaloniaCefBrowser `and its base class. A static ctor initializes a class before the first instance is created or any static members _declared_ in that class (not its base classes) are referenced.

If your example runs on the UI thread, it is safe to say that no exceptions will be thrown on any UI framework

2023-02-27 15:34 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
the example was not the best... but when you reference the class... example calling static method on that same class, the static ctor will run before (just once).

2023-02-27 16:14 UTC, Wiks00 commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
Okay, I think I get your point. Although there are no static members in `BaseCefBrowser`, which means that it is impossible to call it except to create an instance of the class, but it looks like "hidden knowledge".

Unfortunately, I do not see more "native" methods how to call initialization without code duplicates. Would this solution work?

```
        public BaseCefBrowser()
        {
            InitializeInternals();

            _logger = CreateBrowserLogger();

            _adapter = CreateBrowserAdapter();
        }

        public BaseCefBrowser(CefRequestContextSettings cefRequestContextSettings, CefRequestContextHandler cefRequestContextHandler = null)
        {
            InitializeInternals();

            _logger = CreateBrowserLogger();

            CefRequestContext cefRequestContext = CefRequestContext.CreateContext(cefRequestContextSettings, cefRequestContextHandler);

            _adapter = CreateBrowserAdapter(cefRequestContext);
        }

        private void InitializeInternals()
        {
            if (!CefRuntimeLoader.IsLoaded)
            {
                CefRuntimeLoader.Load();
            }
        }

        private ILogger CreateBrowserLogger()
        {

#if HAS_NLOG
            return new Logger(nameof(BaseCefBrowser));
#else
            return new NullLogger(nameof(BaseCefBrowser));
#endif
        }

        private CommonBrowserAdapter CreateBrowserAdapter(CefRequestContext cefRequestContext = null)
            => CefRuntimeLoader.IsOSREnabled ? 
                new CommonOffscreenBrowserAdapter(this, nameof(BaseCefBrowser), CreateOffScreenControlHost(), CreatePopupHost(), _logger, cefRequestContext) : 
                new CommonBrowserAdapter(this, nameof(BaseCefBrowser), CreateControl(), _logger, cefRequestContext);
```

2023-02-27 17:16 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
it doesnt need that many changes, but that wont work either because in order to create a CefRequestContextHandler instance cef dlls need to be loaded. the way I see this working with less changes is as follows:

```
        public BaseCefBrowser(Func<CefRequestContext> requestContextFactory = null)
        {
            if (!CefRuntimeLoader.IsLoaded)
            {
                CefRuntimeLoader.Load();
            }
            
            ...

            RequestContext = requestContextFactory?.Invoke();
        }

2023-02-27 17:44 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +                _adapter = new CommonOffscreenBrowserAdapter(this, nameof(BaseCefBrowser), CreateOffScreenControlHost(), CreatePopupHost(), _logger, cefRequestContextFactory());
watch out the nulls
```suggestion
                _adapter = new CommonOffscreenBrowserAdapter(this, nameof(BaseCefBrowser), CreateOffScreenControlHost(), CreatePopupHost(), _logger, cefRequestContextFactory);
```

2023-02-27 17:44 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +                _adapter = new CommonBrowserAdapter(this, nameof(BaseCefBrowser), CreateControl(), _logger, cefRequestContextFactory());
```suggestion
                _adapter = new CommonBrowserAdapter(this, nameof(BaseCefBrowser), CreateControl(), _logger, cefRequestContextFactory);
```

2023-02-27 17:46 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +        public CommonBrowserAdapter(object eventsEmitter, string name, IControl control, ILogger logger, CefRequestContext cefRequestContext = null)
```suggestion
        public CommonBrowserAdapter(object eventsEmitter, string name, IControl control, ILogger logger, Func<CefRequestContext> cefRequestContextFactory = null)
```

2023-02-27 17:47 UTC, joaompneves commented on CefGlue.Common/CommonBrowserAdapter.cs
> +            RequestContext = cefRequestContext;
```suggestion
            RequestContext = cefRequestContextFactory?.Invoke();
```

2023-02-27 17:57 UTC, Wiks00 commented on CefGlue.Common/BaseCefBrowser.cs
> +                _adapter = new CommonOffscreenBrowserAdapter(this, nameof(BaseCefBrowser), CreateOffScreenControlHost(), CreatePopupHost(), _logger, cefRequestContextFactory());
Sorry, my bad, was too hasty 😅

2023-02-27 18:00 UTC, joaompneves commented on CefGlue.Avalonia/AvaloniaCefBrowser.cs
> +        public AvaloniaCefBrowser(Func<CefRequestContext> cefRequestContextFactory = null)
Dont forget to also change the wpf version... it might not be building

2023-02-27 18:04 UTC, Wiks00 commented on CefGlue.Avalonia/AvaloniaCefBrowser.cs
> +        public AvaloniaCefBrowser(Func<CefRequestContext> cefRequestContextFactory = null)
The build runs without problems, however, due to my interest in Avalonia, I don't quite know how the WPF library works

2023-02-27 18:06 UTC, dmitry-azaraev commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
This is just points to think about, not suggestions to code, nor suggestions to PR:

@joaompneves 
Does Avalonia assumes what Main thread is also always UI thread?
Does CefRuntimeLoader enforces what CEF get initialized on right (Main) thread.

I'm strongly believe what CEF can be initialized on any thread actually, but also this will be mistake - actually it must be initialized only on process's main thread. Everything else is most likely will behave badly and undebuggable in some cases. (On another side - I guess, other platforms requires Main == UI thread anyway, so I guess what this invariant is always true, even on Windows.) Generally CEF/Chromium code should be free from this, but code always have some hidden assumptions, and even it feels like work, did not mean what it works properly. This is why it is easier to init CEF on app startup, just because it is how chrome designed at all (so less cumulative risks).

For one of my projects (windows only and based on self-found mini UI framework (only simple window management and tray menu)), I'm implemented lazy CEF loading only when control is really shown. I'm was focused to use CEF's native message loop, so I'm implemented "replaceable" message loop. So, generally it was close to code above, but triggering initialization happened from paint request, rather than just class creation and custom message loops of course.

The problem what on cold host/os - loading 100+MiB binary is huge traffic even for SSD and lot of work for loader, and might took 100-500-1000ms+ (depending on hardware and OS-related factors). I'm probably even perform dll load on one thread, but initialize on main thread (however, this was years ago, so i'm not sure). Anyway, i'm tried to achieve "true" lazy loading while minimizing as much as possible application window unresponsiveness. Don't underestimate loading times: there is lot of situations when (especially cheap) SSDs go into GC on reads (and oldy HDDs never do it, and behave much better on any load). Your host just perform some writes, and now you just read dll... and, you may get whopping 5-10 seconds lock. Chromium itself uses DLL preloading on Windows very early in `chrome.exe` shim, but for CEF this never true (because client code plays this role of shim). Just to point, what true laziness is trickier than it should, and not so naive as in code above...

Also, if Avalonia allows to create controls on thread another than UI - then `Func<CefRequestContext>` is not enough, because it can be created only at CEF UI thread. Also it might require some setup before use, which currently achievable with sync calls, but this generally not necessary to be true always. E.g. `Func<ValueTask<CefRequestContext>>` can be not bad alternative, allowing performing some async work inside, if it needed.

2023-02-27 18:13 UTC, joaompneves commented on CefGlue.Avalonia/AvaloniaCefBrowser.cs
> +        public AvaloniaCefBrowser(Func<CefRequestContext> cefRequestContextFactory = null)
just make the same change here: https://github.com/OutSystems/CefGlue/blob/main/CefGlue.WPF/WpfCefBrowser.cs
and then build the project
both avalonia and wpf implementations work almost the same, since they share more than 98% of the code

2023-02-27 18:45 UTC, joaompneves commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
>>> Does Avalonia assumes what Main thread is also always UI thread? 
Avalonia assumes the thread where it is initialized to be the UI Thread, so not necessarily the main thread. But likewise WPF, all controls must be created on the UI thread, otherwise and exception is raised.

>>> Does CefRuntimeLoader enforces what CEF get initialized on right (Main) thread.
It doesn't. Probably it should, but thats specific to each UI Framework (Avalonia/WPF), and that piece of code is UI agnostic.
Since CefRuntimeLoader.Load(), calls the cef initialization and according to the [docs](https://github.com/OutSystems/CefGlue/blob/db4b1e74c891f121abc1086126bf217580ecbae7/CefGlue/CefRuntime.cs#L206) it must be called on the main thread. Not doing so, leads to very strange things, because one of the things that cef does is to hook up with the process message loop. On Mac its even more problematic, when cef and the UI thread dont coincide.

In the general case of Desktop apps, and to speedup things, we initialize CEF as soon as we believe it will be used, ie, on the first control instantiation. That way we can save a few milieseconds on the first load, if we considering that not all the work will be done on the UI thread.

@dmitry-azaraev I'm glad you are engaging with this PR, but would be great that you payed some more attention 3 years ago when I first opened the PR on the CefGlue gitlab repo. We did alot of work to create an Avalonia port that can run on Mac and Windows, we separated the browser process with the hosting process, we fixed alot of memory leaks that the original CefGlue implementation has, we introduced a powerfull (strongly typed) ways to comunicate with the browser (js evaluation for .net side, and calling .net code form the browser), we created lots of unit tests... Moreover we have several thousands of users using this every day on an enterprise grade product, and at this point I'm confident with the quality of what we have.
I understand that your interests rely mostly on the core, and alot of our work was done on top of that, but IMO it would be better for the community if we joined efforts, you taking care of the Core (most of our changes on the Core were related with memory leaks fixes) and we could take care of the Avalonia/WPF bindings. My 2 cents.

2023-02-27 20:06 UTC, dmitry-azaraev commented on CefGlue.Common/BaseCefBrowser.cs
> +        }
@joaompneves I'm closed all oldy PRs. I'm can't understand them. There is too much code in once. I'm gladly accept any sensible improvements (or some things which you might require, but it is clear what there is not too many things), but I'm can't accept to merge just bunch of unrelated code. If you maintain updates and need regularly update some things in core - let's discuss them and push them. It should not be a problem. Let's do it if it helps you. Just split core from uncore code, because uncore code is yours anyway and can live separately without harrasing each-other.

As for very "big" plan, what might help community - it would be nice to create new bindings. What's because any CefGlue alternative actually have lot of issues. I'm saying not because they are competitor projects, no. I'm saying because I'm having some unexpected journey with almost all of them as well, and all of them very far from ideal. One of main problems of CefGlue is maintenance hell. And they are solveable. I'm full of new ideas for modern days, it was already started 2-3 times in past years, but never finished (and should be started from zero again, because I'm any way did not remember anything).

Also I'm living in warzone and last year was especially hard, and continues to be hard. Previous years actually was not been too easier, but at least more predictable. Also, just now, I'm not really active CEF user, and by so, I'm doing other Chromium related stuff, and by so, this did not push me actively to change something. CefGlue is very-very-very old project (born in CEF1 era). Few days ago I'm touch generation script because otherwise 108 is was not possible, and this is challenge, because it is dumb script, and everything done is somehow badly (many generators are tricky, but it is tricky twice). Huh. Nowaday, I'm never will write code generator in python.

And main problem with new bindings, what I'm pick (you can read as hire) people(s) for it, and they leave from project without progress. There is was always lot of reasons to do it from 2014, but still this yielded to no progress.

So, just now I'm even not sure what I'm really want to share this work/responsibility with someone, but I'm understand what I'm personally not so interested to make it in only mine hands, as it was in past years. On another side, because I'm know how it must be done in better way - makes me feel bad, because I'm want make it nice.

So, just now, I'm just support it in term of update it time-to-time, not even strictly with every version. Just once in one or two months.

I'm hope what eventually I'm back to more positive mood, and can bring more. But just now this almost impossible. Sorry.

2023-02-28 13:52 UTC, joaompneves commented on CefGlue.WPF/WpfCefBrowser.cs
> +        }
```suggestion
        public WpfCefBrowser() : this(null) { }
```

2023-02-28 14:00 UTC, merged

2023-02-28 14:23 UTC, Wiks00 commented
> Thank you for your contribution. This will be available in nuget version 106.5249.4

Thanks for the help.