Fixing BrowserProcess packaging
OutSystems/CefGlue pull request #78
Opened 2023-02-28 14:48 UTC by osesantos

2023-02-28 15:33 UTC, joaompneves requested changes
I would like to understand why this stopped working. The upgrade shouldn't be related, only possibly the move from .net 5 to .net 6

2023-02-28 15:33 UTC, joaompneves commented on CefGlue.Avalonia/CefGlue.Avalonia.csproj
> +    <PlatformTarget>AnyCPU</PlatformTarget>
is this change required... this doesn't look good because cefglue is x64 only... should not be built as any cpu

2023-02-28 15:33 UTC, joaompneves commented on Nuget.config
> +	</packageRestore>
is this change related/needed?

fix identation

2023-02-28 15:33 UTC, joaompneves commented on Directory.Packages.props
> +        <PackageVersion Include="Avalonia.Diagnostics" Version="0.10.15" />
please revert

2023-02-28 15:33 UTC, joaompneves commented on Directory.Build.targets
> +  <Target Name="PublishBrowserProcessApp" Inputs="(ProjectDir)../.publishbpapp.stamp" Outputs="(ProjectDir)../.publishbpapp.stamp">
this target should be place where its needed

2023-02-28 15:33 UTC, joaompneves commented on Directory.Build.targets
> +  <Target Name="PublishBrowserProcessApp" Inputs="(ProjectDir)../.publishbpapp.stamp" Outputs="(ProjectDir)../.publishbpapp.stamp">
```suggestion
  <Target Name="PublishBrowserProcessApp" Inputs="(ProjectDir)..\.publishbpapp.stamp" Outputs="(ProjectDir)..\.publishbpapp.stamp">
```

2023-02-28 15:33 UTC, joaompneves commented on Directory.Build.targets
> +    <MSBuild Projects="$(ProjectDir)../CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTri
use \ ... / is used when using a prop which msbuild doesn't recognize as path

2023-02-28 15:33 UTC, joaompneves commented on Directory.Build.targets
> +    <Touch Files="$(ProjectDir)../.publishbpapp.stamp" AlwaysCreate="true"/>
this stamp file should go to the obj folder... its the appropriate place for cache files

2023-02-28 15:36 UTC, osesantos commented on Nuget.config
> +	</packageRestore>
using the local packages folder is not very good for project isolation and that was causing us a hard time to troubleshoot problems and test changes locally

2023-02-28 15:37 UTC, osesantos commented on Directory.Packages.props
> +        <PackageVersion Include="Avalonia.Diagnostics" Version="0.10.15" />
no, we agreed that the avalonia version would be upgraded on his own pr and version

2023-02-28 15:41 UTC, osesantos commented on Directory.Build.targets
> +  <Target Name="PublishBrowserProcessApp" Inputs="(ProjectDir)../.publishbpapp.stamp" Outputs="(ProjectDir)../.publishbpapp.stamp">
I disagree because this target acts on the BrowserProcess project but is being called by the Common project which means that from an organization's point of view, it should be placed in a place that is common to both projects.

2023-02-28 15:42 UTC, joaompneves commented on CefGlue.Avalonia/CefGlue.Avalonia.csproj
> +    <PlatformTarget>AnyCPU</PlatformTarget>
thats an SS problem... not cefglue

2023-02-28 15:44 UTC, osesantos commented on Directory.Build.targets
> +    <MSBuild Projects="$(ProjectDir)../CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTri
actually, I think it does, .net6 changed that, and the proof of that is the tests I did both on win, mac, and the pipeline. 
But to keep consistency with other targets on this solution I'll change it

2023-02-28 15:45 UTC, joaompneves commented on Directory.Packages.props
> +        <PackageVersion Include="Avalonia.Diagnostics" Version="0.10.15" />
but its a downgrade

2023-02-28 15:46 UTC, joaompneves commented on Directory.Build.targets
> +  <Target Name="PublishBrowserProcessApp" Inputs="(ProjectDir)../.publishbpapp.stamp" Outputs="(ProjectDir)../.publishbpapp.stamp">
that was not a problem before... it was placed on the browser process project... still not clear for me the need of these so many changes

2023-02-28 15:48 UTC, joaompneves commented on Directory.Build.targets
> +    <MSBuild Projects="$(ProjectDir)../CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTri
do you have a documented proof? that would be a major breaking change which I0m a bit skeptical that they would introduce that

2023-02-28 16:26 UTC, osesantos commented on Directory.Build.targets
> +    <Touch Files="$(ProjectDir)../.publishbpapp.stamp" AlwaysCreate="true"/>
ok even so I disagree because this target is common to all projects, creating the stamp on the build folder of the BrowserProcess feels to me like a hack. However, I don't foresee any impact on the final output of the nuget so Im ok on moving that it to the build

2023-02-28 16:49 UTC, osesantos commented on Directory.Build.targets
> +    <MSBuild Projects="$(ProjectDir)../CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTri
https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats
![image](https://user-images.githubusercontent.com/20876378/221920990-535614ef-61cd-44a0-b497-5b0cfb258304.png)
By using / we are both enabling building on win and mac

2023-02-28 16:53 UTC, osesantos commented on Directory.Build.targets
> +  <Target Name="PublishBrowserProcessApp" Inputs="(ProjectDir)../.publishbpapp.stamp" Outputs="(ProjectDir)../.publishbpapp.stamp">
yes, it was on the browser process, but the target that is on the common is dependent on this one to actually copy this target output into the nuget. This way the target is available on the Common project

2023-02-28 16:56 UTC, osesantos commented on Directory.Packages.props
> +        <PackageVersion Include="Avalonia.Diagnostics" Version="0.10.15" />
sure, we were seeing some build processes being left running even after the build was finished alongside with Avalonia dlls being locked. I want to avoid more external changes and validate these ones first. btw, the upgrade was made by @cangosta on his pr

2023-02-28 16:59 UTC, osesantos commented on CefGlue.Avalonia/CefGlue.Avalonia.csproj
> +    <PlatformTarget>AnyCPU</PlatformTarget>
its also a cefglue problem because we dont want SS platform to be locked to the one used by cefglue.

2023-02-28 17:08 UTC, osesantos commented on Directory.Build.targets
> +    <Touch Files="$(ProjectDir)../.publishbpapp.stamp" AlwaysCreate="true"/>
![image](https://user-images.githubusercontent.com/20876378/221925783-cdad42a9-8350-4540-9951-23cf6fdd7a3e.png)
sorry but I can't do it... I guess the build folder is not yet available when this target executes

2023-02-28 17:29 UTC, joaompneves commented on CefGlue.Avalonia/CefGlue.Avalonia.csproj
> +    <PlatformTarget>AnyCPU</PlatformTarget>
It needs to be locked.. it simply wont work. Cefglue doesnt support x86 architecture anymore. Running on x86 will crash right away.

2023-03-01 09:24 UTC, osesantos commented on CefGlue.Avalonia/CefGlue.Avalonia.csproj
> +    <PlatformTarget>AnyCPU</PlatformTarget>
fair point, however, we will have to revisit this in the future since we will want to native ARM builds

2023-03-01 09:30 UTC, osesantos commented on Directory.Packages.props
> +        <PackageVersion Include="Avalonia.Diagnostics" Version="0.10.15" />
I locally tested it and reverting the version allowed me to get it working
also, by running the build via the terminal we can see on the task manager that some processes are left running, if we try to git clean then you can see that Avalonia.task.dll is locked. Ending those processes unlocks the dll

2023-03-01 09:40 UTC, osesantos commented on Directory.Build.targets
> +    <MSBuild Projects="$(ProjectDir)../CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTri
sorry, I think I'm missing something... if I can use / or \ for paths and should use / for text to allow cross-platform compilation, why not just use /  everywhere?

2023-03-01 10:01 UTC, joaompneves commented on Directory.Build.targets
> +    <MSBuild Projects="$(ProjectDir)../CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTri
because editors (VS, Rider) prefer \ ... that would be a lost game trying to fight with that... so the "best" rule is what I described

2023-03-01 10:38 UTC, osesantos commented on Directory.Packages.props
> +        <PackageVersion Include="Avalonia.Diagnostics" Version="0.10.15" />
reverted back to 17

2023-03-01 10:39 UTC, osesantos commented on Nuget.config
> +	</packageRestore>
identation fixed

2023-03-01 11:27 UTC, alvesmiguel1 commented on Directory.Build.targets
> +    <!-- Publish both platforms on Windows for packaging -->
We are now publishing in both operating systems, right?

2023-03-01 11:28 UTC, alvesmiguel1 commented on Directory.Build.targets
> +    <!-- Publish both platforms on Windows for packaging -->
Since you removed the `IsWindows` property

2023-03-01 11:42 UTC, joaompneves commented on .gitignore
> +**/*.stamp
not needed since stamp files are inside obj

2023-03-01 11:42 UTC, joaompneves commented on Directory.Build.targets
> +  </Target>
```suggestion
  <PropertyGroup>
      <BrowserProcessAppPublishStamp>$(IntermediateOutputPath)BrowserProcessAppPublish.stamp</BrowserProcessAppPublishStamp>
  </PropertyGroup>
  
  <Target Name="PublishBrowserProcessApp" Inputs="$(BrowserProcessAppPublishStamp)" Outputs="$(BrowserProcessAppPublishStamp)">
    <!-- Publish both platforms on Windows for packaging -->
    <Message Text="Publishing BrowserProcess... [$(ProjectPath)]" Importance="High" />
    <MSBuild Projects="$(ProjectDir)..\CefGlue.BrowserProcess\CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTrimmed=True;RuntimeIdentifier=win-x64" />
    <MSBuild Projects="$(ProjectDir)..\CefGlue.BrowserProcess\CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishTrimmed=True;RuntimeIdentifier=osx-x64" />
    <Touch Files="$(BrowserProcessAppPublishStamp)" AlwaysCreate="true"/>
  </Target>
```

2023-03-01 15:55 UTC, osesantos commented on Directory.Build.targets
> +  </Target>
why this change to IntermediateOutputPath? won't that path depend on the project that is calling it? that was not what I wanted, the stamp is to avoid the PublishBrowserProcessApp more than once when called by multiple projects

2023-03-01 16:12 UTC, joaompneves commented on Directory.Build.targets
> +  </Target>
the target will be called by the common project, hence it will store the stamp on the common project intermediate folder. Thats why I also suggested the target to be moved to the common project... its where it makes sense.

2023-03-01 16:16 UTC, joaompneves commented on Directory.Build.targets
> +  </Target>
Moreover have you tried building the whole project, then making a change on the browser process project and build the demo again? will the browser process be built again and take the new change?

2023-03-01 16:18 UTC, joaompneves commented on Directory.Build.targets
> +    <!-- Publish both platforms on Windows for packaging -->
previously we only built both when on windows, because the azure pipeline runs on windows... any good reason for that change?

2023-03-01 16:25 UTC, osesantos commented on Directory.Build.targets
> +  </Target>
> Moreover have you tried building the whole project, then making a change on the browser process project and building the demo again? will the browser process be built again and take the new change?
the objective of this target is not to be called each time the BrowserProcess is built, but instead be called when we are creating the Common NuGet, this is because we are shipping the BrowserProcess inside the Common instead of shipping it on its own NuGet.
To answer your question, yes the BrowserProcess will be built again, will this target run? no, we have to delete the stamp or create a clean target to do that. That is why I still think that having it on the root was better to identify it and remove it if needed.

2023-03-01 16:33 UTC, osesantos commented on Directory.Build.targets
> +    <!-- Publish both platforms on Windows for packaging -->
if we want to change the pipeline to ubuntu, for instance, this will be a blocker. I don't see any advantage in having that type of condition if we always want the NuGet to have both win and osx available regardless of the OS that is building it.

2023-03-01 16:40 UTC, joaompneves commented on Directory.Build.targets
> +  </Target>
thats big deal... because if you make changes you wont be able to see those changes. that needs to be fixed

2023-03-01 16:41 UTC, joaompneves commented on Directory.Build.targets
> +    <!-- Publish both platforms on Windows for packaging -->
is that a problem? is that what you're trying to fix? stick with the minimal changes required, please. unless you're willing to buy new problems

2023-03-02 15:35 UTC, joaompneves commented on CefGlue.Common/CefGlue.Common.csproj
> +        <ProjectReference Include="..\CefGlue.BrowserProcess\CefGlue.BrowserProcess.csproj">
```suggestion
        <!-- Forces BrowserProcess build before CopyProjectReferencesToPackage target run -->
        <ProjectReference Include="..\CefGlue.BrowserProcess\CefGlue.BrowserProcess.csproj">
```

2023-03-02 15:59 UTC, joaompneves approved these changes

2023-03-02 16:13 UTC, merged