Fix Linux X64 Port
OutSystems/CefGlue pull request #88
Opened 2023-05-18 20:38 UTC by pheonixfirewingz

Fix NativeLibsLoader to allow Linux to run CefGlue.Tests

I did a bit of debugging of CefGlue.Tests, CefGlue.Common and CefGlue.Shared and the only thing stopping it from running was in NativeLibsLoader I did need to put the libcef.so in the run area built that is another thing to look at or discuss

2023-05-18 20:41 UTC, pheonixfirewingz commented
I read, understood and accept the OutSystems CLA

2023-05-19 08:09 UTC, joaompneves commented on CefGlue.BrowserProcess/Helpers/NativeLibsLoader.cs
> +                case CefRuntimePlatform.Linux:
```suggestion
                    break;

                case CefRuntimePlatform.Linux:
```

2023-05-19 10:35 UTC, pheonixfirewingz commented
> This means that putting libcef, and their dependencies on the appropriate places, tests and the sample app runs ok?

yes as far as i have tested but before merging would be nice to get a second opinion

2023-05-19 10:43 UTC, pheonixfirewingz commented
> Well in order to be tested its missing the cef libs.

i'm new to the side of packaging with nuget so how would i set that up?

2023-05-19 12:30 UTC, pheonixfirewingz commented
i have the package ready with the binarys but idk how to register it to nuget https://github.com/pheonixfirewingz/cef.redist.linux

2023-05-19 12:58 UTC, joaompneves commented
You need to create a nuget account, build the package and and upload the package to nuget.

2023-05-19 13:07 UTC, pheonixfirewingz commented
> You need to create a nuget account, build the package and and upload the package to nuget.

I’m stuck on the building part 😅

2023-05-19 13:42 UTC, joaompneves commented
so you need to execute the script and then run nuget pack:
```
nuget pack cef.redist.linux64.nuspec -Properties version=106.0.26

2023-05-19 14:54 UTC, pheonixfirewingz commented
i've ran into a problem of the .nupkg being to big for nuget.org at 352mb any idea how I can shrink it

2023-05-19 15:13 UTC, joaompneves commented
They say that the limit is 500mb per file (https://learn.microsoft.com/en-us/azure/devops/artifacts/reference/limits?view=azure-devops)

Nevertheless the file size of libcef on linux is absurd (1.9GB uncompressed), comparing to windows and mac (185mb).

2023-05-20 11:12 UTC, riboyama commented
> i've ran into a problem of the .nupkg being to big for nuget.org at 352mb any idea how I can shrink it

If you're on Ubuntu you can try to strip the debug symbols of the native library files.
```
strip libcef.so
strip libEGL.so
strip libGLESv2.so
strip libvk_swiftshader.so
strip libvulkan.so.1
```

This should reduce the total file size significantly on linux-x64, and just plain up remove a gigabyte on linux-arm64

2023-05-22 09:07 UTC, pheonixfirewingz commented
just an update but i'm editing the script to include the stript feature

2023-05-22 09:19 UTC, pheonixfirewingz commented
![Screenshot (27)](https://github.com/OutSystems/CefGlue/assets/26938574/b1d03f15-bf79-4c5c-b546-5bb06358cfc9)
I used wsl2 to generate it due to me not able to use nuget.exe on linux directly

2023-05-22 09:29 UTC, joaompneves commented
The package doesn't seem ok. Where are the cef libs?

<img width="340" alt="Screenshot 2023-05-22 at 10 26 10" src="https://github.com/OutSystems/CefGlue/assets/693294/af13e4f6-fb31-4e50-8f20-0ec46eae1b79">

2023-05-22 09:33 UTC, pheonixfirewingz commented
I don't have access to the asus piplines to set up the tests for linux so will need one of the admin maintairs to sort that out

2023-05-22 09:36 UTC, pheonixfirewingz commented
@joaompneves the ball is now in your court to see if this is good enough to be mearged or if i need to do more work to get this to repo standards

2023-05-22 09:53 UTC, joaompneves requested changes
Also needs changes:

- https://github.com/OutSystems/CefGlue/blob/f4fac1e5e5c1bb22b1400ccd914782c9891f5414/CefGlue.Common/CefGlue.Common.csproj#L53
- https://github.com/OutSystems/CefGlue/blob/55bfefb79e16ff07cf6db61d20c797a95249f71a/CefGlue.Common/build/CefGlue.Common.targets#L15
- https://github.com/OutSystems/CefGlue/blob/55bfefb79e16ff07cf6db61d20c797a95249f71a/CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj#L9
- https://github.com/OutSystems/CefGlue/blob/55bfefb79e16ff07cf6db61d20c797a95249f71a/CefGlue.BrowserProcess/CefGlue.BrowserProcess.csproj#L36
- https://github.com/OutSystems/CefGlue/blob/55bfefb79e16ff07cf6db61d20c797a95249f71a/CefGlue.Common/build/CefGlue.Common.props#L4

2023-05-22 09:53 UTC, joaompneves commented on Directory.Packages.props
> +        <PackageVersion Include="cef.redist.linux64" Version="$(CefRedistOSXVersion)" />
need a new variable for setting the linux version independently

2023-05-22 10:44 UTC, joaompneves commented
Tried producing the nuget on out pipeline and seems ok
<img width="733" alt="Screenshot 2023-05-22 at 11 44 16" src="https://github.com/OutSystems/CefGlue/assets/693294/ebc149e2-7d17-468f-b3a6-2b9e568bde32">

2023-05-22 10:49 UTC, joaompneves commented
We can produce the package and publish it to our nuget account if you don't mind. The one thing I cannot guarantee is ensuring a working linux version (we can produce the artifacts but we wont run/test it or maintain it), since we don't need linux support for now and we don't have linux machines.

2023-05-22 10:55 UTC, pheonixfirewingz commented
> We can produce the package and publish it to our nuget account if you don't mind. The one thing I cannot guarantee is ensuring a working linux version (we can produce the artifacts but we wont run/test it or maintain it), since we don't need linux support for now and we don't have linux machines.

https://www.nuget.org/packages/cef.redist.linux64/106.0.27

2023-05-22 11:04 UTC, pheonixfirewingz commented
> We can produce the package and publish it to our nuget account if you don't mind. The one thing I cannot guarantee is ensuring a working linux version (we can produce the artifacts but we wont run/test it or maintain it), since we don't need linux support for now and we don't have linux machines.

if you use azus testing will it not be posible to set up a linx test?

2023-05-22 11:10 UTC, pheonixfirewingz commented
@joaompneves i can't check why CefGlue failed could you have a look please

2023-05-22 11:24 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +        <None Include="@(CefRedistOSX64)">
```suggestion
        <None Include="@(CefRedistLinux64)">
```

Also needs to be changed here:
https://github.com/pheonixfirewingz/cef.redist.linux/blob/main/build/cef.redist.linux64.props#L4

2023-05-22 11:24 UTC, joaompneves commented on CefGlue.Common/build/CefGlue.Common.targets
> +        <ItemGroup Condition="'$(CefGlueTargetPlatform)' == 'linux'">
```suggestion
    <ItemGroup Condition="'$(CefGlueTargetPlatform)' == 'linux'">
```

2023-05-22 11:26 UTC, pheonixfirewingz commented on CefGlue.Common/build/CefGlue.Common.targets
> +        <ItemGroup Condition="'$(CefGlueTargetPlatform)' == 'linux'">
ok again thanks for you time i'll get to work on it

2023-05-22 11:30 UTC, joaompneves commented
> > We can produce the package and publish it to our nuget account if you don't mind. The one thing I cannot guarantee is ensuring a working linux version (we can produce the artifacts but we wont run/test it or maintain it), since we don't need linux support for now and we don't have linux machines.
> 
> if you use azus testing will it not be posible to set up a linx test?

We run automatic tests on Windows. And we do manual validation on mac, due to some mac nunit/threading limitations.

> i can't check why CefGlue failed could you have a look please

It failing big time. Not sure why.

```
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed
Results File: D:\a\_temp\VssAdministrator_WIN-EPGTCKQ0DC2_2023-05-22_11_22_48.trx

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
```

2023-05-22 11:36 UTC, pheonixfirewingz commented
> 

could it be down to the cross confict i cause in the build system you asked me to resolve

2023-05-22 11:50 UTC, pheonixfirewingz commented
is there no why to set up a linux machine like mac?

2023-05-22 11:52 UTC, pheonixfirewingz commented
@joaompneves CefGlue failed again could you have a look please

2023-05-22 13:04 UTC, joaompneves commented
Its complaining with a missing package `cef.redist.linux64 (>= 106.0.27-patch1) but cef.redist.linux64 106.0.27-patch1 was not found`

2023-05-22 13:08 UTC, joaompneves commented
> > We run automatic tests on Windows. And we do manual validation on mac, due to some mac nunit/threading limitations.
> 
> is there no why to set up a linux machine like mac?

As I said we are only able to run automatic tests on Windows. On mac it wont run, due to the limitations I described before. We cant invest more on linux because we simply don't need/use it. We can accept PRs but that ends there. Sorry.

2023-06-05 08:37 UTC, joaompneves commented
Any news?

2023-06-06 14:35 UTC, pheonixfirewingz commented
After my last message events in my life made me have to put the coding on back burner so will do testing, fixing and updating as soon as I am able.

2023-08-02 17:03 UTC, Rosentti commented
I tested this PR and it unfortunately didn't work. I tried the `CefGlue.Demo.Avalonia`, and it failed with:
```
[onni@onskankone net6.0]$ ./Xilium.CefGlue.Demo.Avalonia 
The application to execute does not exist: '/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/Xilium.CefGlue.BrowserProcess.dll'.
The application to execute does not exist: '/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/Xilium.CefGlue.BrowserProcess.dll'.
Trace/breakpoint trap (core dumped)
```
Here's the stack trace as well, at least we're getting into cef code before crashing:
<details>
<summary>Stacktrace</summary>

```
 Stack trace of thread 229515:
                #0  0x00007f9f07c3d36b n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x3e3d36b)
                #1  0x00007f9f097e982b n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x59e982b)
                #2  0x00007f9f0715f42f n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x335f42f)
                #3  0x00007f9f07041413 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x3241413)
                #4  0x00007f9f097e8c32 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x59e8c32)
                #5  0x00007f9f097e661a n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x59e661a)
                #6  0x00007f9f05f70836 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x2170836)
                #7  0x00007f9f05f70676 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x2170676)
                #8  0x00007f9f05f486f9 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x21486f9)
                #9  0x00007f9f05f48413 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x2148413)
                #10 0x00007f9f05ec2368 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/libcef.so + 0x20c2368)
                #11 0x00007f9f86f35d5c n/a (n/a + 0x0)
                #12 0x00007f9f86f33e5d n/a (n/a + 0x0)
                #13 0x00007f9f86f2fdc3 n/a (n/a + 0x0)
                #14 0x00007f9f86f2f497 n/a (n/a + 0x0)
                #15 0x00007f9f86f2f400 n/a (n/a + 0x0)
                #16 0x00007f9f86f2eeeb n/a (n/a + 0x0)
                #17 0x00007f9f86f2dc07 n/a (n/a + 0x0)
                #18 0x00007f9f86f24230 n/a (n/a + 0x0)
                #19 0x00007f9f86f22f8d n/a (n/a + 0x0)
                #20 0x00007f9f86dd2356 n/a (n/a + 0x0)
                #21 0x00007f9f86db17f6 n/a (n/a + 0x0)
                #22 0x00007f9f86db172e n/a (n/a + 0x0)
                #23 0x00007f9f859c56f8 n/a (n/a + 0x0)
                #24 0x00007f9f859c523c n/a (n/a + 0x0)
                #25 0x00007f9f8550ca4a n/a (n/a + 0x0)
                #26 0x00007f9f85503a96 n/a (n/a + 0x0)
                #27 0x00007f9ffe96e0b7 n/a (libcoreclr.so + 0x36e0b7)
                #28 0x00007f9ffe7ae05e n/a (libcoreclr.so + 0x1ae05e)
                #29 0x00007f9ffe68d8b5 n/a (libcoreclr.so + 0x8d8b5)
                #30 0x00007f9ffe68dbc2 n/a (libcoreclr.so + 0x8dbc2)
                #31 0x00007f9ffe6c0dc2 n/a (libcoreclr.so + 0xc0dc2)
                #32 0x00007f9ffe678117 coreclr_execute_assembly (libcoreclr.so + 0x78117)
                #33 0x00007f9ffed5d986 n/a (libhostpolicy.so + 0x15986)
                #34 0x00007f9ffed5dc6e n/a (libhostpolicy.so + 0x15c6e)
                #35 0x00007f9ffed5e5c6 corehost_main (libhostpolicy.so + 0x165c6)
                #36 0x00007f9ffeda572b n/a (libhostfxr.so + 0x1072b)
                #37 0x00007f9ffeda474c n/a (libhostfxr.so + 0xf74c)
                #38 0x00007f9ffeda0f78 hostfxr_main_startupinfo (libhostfxr.so + 0xbf78)
                #39 0x0000562a6519ba25 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/Xilium.CefGlue.Demo.Avalonia + 0x10a25)
                #40 0x0000562a6519bef0 n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/Xilium.CefGlue.Demo.Avalonia + 0x10ef0)
                #41 0x00007f9ffee14850 n/a (libc.so.6 + 0x23850)
                #42 0x00007f9ffee1490a __libc_start_main (libc.so.6 + 0x2390a)
                #43 0x0000562a6518fd7a n/a (/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/Xilium.CefGlue.Demo.Avalonia + 0x4d7a)
                ELF object binary architecture: AMD x86-64
```
</details>

2023-09-03 06:57 UTC, haizzh commented
Any news for this PR? I'm looking forward to this PR

2023-09-05 10:53 UTC, pheonixfirewingz commented
I've been extremely busy due to some life events and have not had time to work on it if anyone wants to have a look at my work and finish it feel free to

2023-10-13 18:52 UTC, bogatkov commented
> I tested this PR and it unfortunately didn't work. I tried the `CefGlue.Demo.Avalonia`, and it failed with:
> 
> ```
> [onni@onskankone net6.0]$ ./Xilium.CefGlue.Demo.Avalonia 
> The application to execute does not exist: '/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/Xilium.CefGlue.BrowserProcess.dll'.
> The application to execute does not exist: '/home/onni/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net6.0/Xilium.CefGlue.BrowserProcess.dll'.
> Trace/breakpoint trap (core dumped)
> ```
> 
> Here's the stack trace as well, at least we're getting into cef code before crashing:
> 
> Stacktrace

I tested this PR on Ubuntu 18.04 and the same occurred.

I added some lines [here at the BrowserCefApp.OnBeforeCommandLineProcessing](https://github.com/pheonixfirewingz/CefGlue/blob/main/CefGlue.Common/BrowserCefApp.cs#L20):

```c#
                if (CefRuntime.Platform == CefRuntimePlatform.Linux)
                {
                    commandLine.AppendSwitch("no-zygote");
                }
```

and [here at the CefRuntimeLoader.InternalInitialize](https://github.com/pheonixfirewingz/CefGlue/blob/main/CefGlue.Common/CefRuntimeLoader.cs#L22):

```c#
                case CefRuntimePlatform.Linux:
                    string localesPath = Path.Combine(basePath, "locales");
                    if (Directory.Exists(localesPath))
                    {
                        settings.LocalesDirPath = localesPath;
                    }

                    settings.NoSandbox = true;
                    settings.MultiThreadedMessageLoop = false;
                    settings.ExternalMessagePump = true;
                    settings.ResourcesDirPath = basePath;
                    break;
```

Unfortunately, the CEF code still crashed with **Segmentation fault**.

2023-11-16 16:20 UTC, Haltroy commented
Applied the same stuff mentioned by [this comment](https://github.com/OutSystems/CefGlue/pull/88#issuecomment-1762037725) (except switched `settings.MultiThreadedMessageLoop` to `true` and `settings.ExternalMessagePump` to `false` in [CefRuntimeLoader.InternalInitialize](https://github.com/pheonixfirewingz/CefGlue/blob/main/CefGlue.Common/CefRuntimeLoader.cs#L22) but it didn't change anything). It always crashes on [CefGlue/CefGlue/CefRuntime.cs line 227 `libcef.initialize(n_main_args, n_settings, n_app, (void*)windowsSandboxInfo)`](https://github.com/pheonixfirewingz/CefGlue/blob/main/CefGlue/CefRuntime.cs#L227).

2023-11-16 16:45 UTC, Haltroy commented
Update: I remebered that some stuff had to be set in order to get a display back when I was using CefNet (which is now dead) and checked some my old stuff and I only had to enable `settings.WindowlessRenderingEnabled` in [CefRuntimeLoader.InternalInitialize](https://github.com/pheonixfirewingz/CefGlue/blob/main/CefGlue.Common/CefRuntimeLoader.cs#L22):
![google-cefglue](https://github.com/OutSystems/CefGlue/assets/30141424/f2f2dff1-7b62-4d29-83b4-f8bcc685c7b4)

2023-11-20 10:23 UTC, joaompneves commented
Please feel free to open a PR

2023-11-20 12:40 UTC, Haltroy commented
> Please feel free to open a PR

PR #119 is up, somehow failed in both checks and my machine. Also I didn't include changes for Linux ARM64 and will add them if that's OK.

2024-02-10 04:23 UTC, BhupiMAD commented
Any progress on making it work on arm64 linux? 
there is not a single solution available that would make embedded browser work on linux arm64 with c#. Any solution on linux would be highly appreciated by the community. There is only one company that is successful and it asks for 11k for licensing.

2024-02-14 10:05 UTC, joaompneves commented
Some people have asked, some people tried opening PRs, but no one managed to make it make it work until now.

2024-02-18 19:00 UTC, Haltroy commented
> Any progress on making it work on arm64 linux? there is not a single solution available that would make embedded browser work on linux arm64 with c#. Any solution on linux would be highly appreciated by the community. There is only one company that is successful and it asks for 11k for licensing.

Started working on porting CefGlue to Linux again, this time for both x64 and ARM64. The binary package for CEF ARM64 is available [here](https://www.nuget.org/packages/cef.bin.linuxarm64/) and the repository for generatng NuGet packages are [here](https://github.com/Haltroy/cef.bin.linux).

2024-02-18 19:03 UTC, pheonixfirewingz commented
I've not had time to work on this due to me starting university but if you have at binary i could see if i could get the package sorted on nuget it's nice to see someone taking up the work i couldn't 🙂

2024-02-18 19:23 UTC, Haltroy commented
In my first try, I copied your edits and applied directly to a newer code and changed stuff around. It didn't go well and I ran out of time, had to work on my midterms (I'm also university student too).

This time, I decided to not make a PR with 11 commits in a day that basically won't change anything. So I just temporarily forked this project (available [here](https://github.com/Haltroy/CefGlue)) and I'm trying to make it work. Currently resolved libcef not loading by forcing it to load (by searching it in the entire application folder and its subdirectories) to memory just before checking its version. 

Currently, it won't display anything until I run it in OSR mode or just randomly crash on stuff which these 2 bugs I'm trying to investigate.

2024-07-31 08:52 UTC, joaompneves commented
Now available: [120.6099.204](https://www.nuget.org/packages/CefGlue.Avalonia/120.6099.204)

2024-07-31 08:52 UTC, closed without merging

2024-07-31 08:55 UTC, BhupiMAD commented
So its supports arm64 now?

2024-07-31 08:59 UTC, joaompneves commented
https://github.com/OutSystems/CefGlue/blob/main/LINUX.md